/**
 * Product keys — Client profile — who someone is and how to reach them.
 *
 * One slice of the catalogue that used to be all 1,637 lines of
 * `keyManagerConstants.ts`. That file still composes these into
 * `ALL_PRODUCT_KEYS` and dispatches them from `getKeysByCategory`; it just no
 * longer holds the definitions itself.
 */
import type { ProductKey } from '../../types/product-keys';

// Profile: Personal Information Keys
export const PROFILE_PERSONAL_KEYS: ProductKey[] = [
  {
    id: 'profile_title',
    category: 'profile_personal',
    name: 'Title',
    description: 'Client title (Mr, Mrs, Dr, etc.)',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_first_name',
    category: 'profile_personal',
    name: 'First Name',
    description: 'Client first name',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_middle_name',
    category: 'profile_personal',
    name: 'Middle Name',
    description: 'Client middle name',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_last_name',
    category: 'profile_personal',
    name: 'Last Name',
    description: 'Client last name',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_date_of_birth',
    category: 'profile_personal',
    name: 'Date of Birth',
    description: 'Client date of birth',
    dataType: 'date',
    isCalculated: false,
  },
  {
    id: 'profile_gender',
    category: 'profile_personal',
    name: 'Gender',
    description: 'Client gender',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_nationality',
    category: 'profile_personal',
    name: 'Nationality',
    description: 'Client nationality',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_marital_status',
    category: 'profile_personal',
    name: 'Marital Status',
    description: 'Client marital status',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_marital_regime',
    category: 'profile_personal',
    name: 'Marital Regime',
    description: 'Marriage contract type (In Community of Property, etc.)',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_id_number',
    category: 'profile_personal',
    name: 'ID Number',
    description: 'National ID number',
    dataType: 'text',
    isCalculated: false,
  },
];

// Profile: Contact Information Keys
export const PROFILE_CONTACT_KEYS: ProductKey[] = [
  {
    id: 'profile_email',
    category: 'profile_contact',
    name: 'Email Address',
    description: 'Primary email address',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_secondary_email',
    category: 'profile_contact',
    name: 'Secondary Email',
    description: 'Secondary email address',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_phone_number',
    category: 'profile_contact',
    name: 'Phone Number',
    description: 'Primary phone number',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_alternative_phone',
    category: 'profile_contact',
    name: 'Alternative Phone',
    description: 'Alternative phone number',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_preferred_contact_method',
    category: 'profile_contact',
    name: 'Preferred Contact Method',
    description: 'Client preferred contact method',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_emergency_contact_name',
    category: 'profile_contact',
    name: 'Emergency Contact Name',
    description: 'Name of emergency contact person',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_emergency_contact_relationship',
    category: 'profile_contact',
    name: 'Emergency Contact Relationship',
    description: 'Relationship to emergency contact',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_emergency_contact_phone',
    category: 'profile_contact',
    name: 'Emergency Contact Phone',
    description: 'Emergency contact phone number',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_emergency_contact_email',
    category: 'profile_contact',
    name: 'Emergency Contact Email',
    description: 'Emergency contact email address',
    dataType: 'text',
    isCalculated: false,
  },
];

// Profile: Identity Keys
export const PROFILE_IDENTITY_KEYS: ProductKey[] = [
  {
    id: 'profile_id_country',
    category: 'profile_identity',
    name: 'ID Country',
    description: 'Country of ID document',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_passport_country',
    category: 'profile_identity',
    name: 'Passport Country',
    description: 'Country of passport issuance',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_passport_number',
    category: 'profile_identity',
    name: 'Passport Number',
    description: 'Passport number',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_tax_number',
    category: 'profile_identity',
    name: 'Tax Number',
    description: 'Tax reference number',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_permit_number',
    category: 'profile_identity',
    name: 'Work Permit Number',
    description: 'Work permit or visa number',
    dataType: 'text',
    isCalculated: false,
  },
];

// Profile: Address Keys
export const PROFILE_ADDRESS_KEYS: ProductKey[] = [
  {
    id: 'profile_residential_address_line1',
    category: 'profile_address',
    name: 'Residential Address Line 1',
    description: 'Residential street address line 1',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_address_line2',
    category: 'profile_address',
    name: 'Residential Address Line 2',
    description: 'Residential street address line 2',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_suburb',
    category: 'profile_address',
    name: 'Residential Suburb',
    description: 'Residential suburb',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_city',
    category: 'profile_address',
    name: 'Residential City',
    description: 'Residential city',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_province',
    category: 'profile_address',
    name: 'Residential Province',
    description: 'Residential province or state',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_postal_code',
    category: 'profile_address',
    name: 'Residential Postal Code',
    description: 'Residential postal code',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_residential_country',
    category: 'profile_address',
    name: 'Residential Country',
    description: 'Residential country',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_address_line1',
    category: 'profile_address',
    name: 'Work Address Line 1',
    description: 'Work street address line 1',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_address_line2',
    category: 'profile_address',
    name: 'Work Address Line 2',
    description: 'Work street address line 2',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_suburb',
    category: 'profile_address',
    name: 'Work Suburb',
    description: 'Work suburb',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_city',
    category: 'profile_address',
    name: 'Work City',
    description: 'Work city',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_province',
    category: 'profile_address',
    name: 'Work Province',
    description: 'Work province or state',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_postal_code',
    category: 'profile_address',
    name: 'Work Postal Code',
    description: 'Work postal code',
    dataType: 'text',
    isCalculated: false,
  },
  {
    id: 'profile_work_country',
    category: 'profile_address',
    name: 'Work Country',
    description: 'Work country',
    dataType: 'text',
    isCalculated: false,
  },
];
