/**
 * ReviewQueue — Auto-Generated Article Draft Review Queue
 *
 * Filtered view of articles created by automation pipelines (last_edited_by
 * starts with "auto:"). Provides bulk approve/publish and schedule actions
 * so editors can efficiently process the drafts queue.
 *
 * Pipeline source badges let editors see which pipeline generated each article
 * at a glance, and the bulk-select workflow matches the existing
 * ArticlesListView patterns.
 *
 * @module publications/components/ReviewQueue
 */

import React, { useState, useMemo, useCallback } from 'react';
import { Button } from '../../../../ui/button';
import { Badge } from '../../../../ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '../../../../ui/card';
import { Checkbox } from '../../../../ui/checkbox';
import {
  Eye,
  Edit,
  Send,
  Calendar,
  Clock,
  CheckCircle2,
  Loader2,
  Inbox,
  Zap,
  Newspaper,
  Scale,
  CalendarDays,
  BarChart3,
  Trash2,
  Image as ImageIcon,
  FolderOpen,
} from 'lucide-react';
import { cn } from '../../../../ui/utils';
import { toast } from 'sonner@2.0.3';
import { PublicationsAPI } from '../api';
import { StatusBadge } from './StatusBadge';
import { formatDate, getRelativeTime, truncateText } from '../utils';
import type { Article, Category } from '../types';

// ---------------------------------------------------------------------------
// Pipeline display config — config-driven per Guidelines §5.3
// ---------------------------------------------------------------------------

const PIPELINE_CONFIG = {
  'auto:market_commentary': {
    label: 'Market Commentary',
    shortLabel: 'Market',
    icon: BarChart3,
    badgeClass: 'bg-blue-100 text-blue-700 border-blue-200',
  },
  'auto:regulatory_monitor': {
    label: 'Regulatory Monitor',
    shortLabel: 'Regulatory',
    icon: Scale,
    badgeClass: 'bg-purple-100 text-purple-700 border-purple-200',
  },
  'auto:news_commentary': {
    label: 'News Commentary',
    shortLabel: 'News',
    icon: Newspaper,
    badgeClass: 'bg-amber-100 text-amber-700 border-amber-200',
  },
  'auto:calendar_content': {
    label: 'Calendar Content',
    shortLabel: 'Calendar',
    icon: CalendarDays,
    badgeClass: 'bg-green-100 text-green-700 border-green-200',
  },
} as const;

type PipelineKey = keyof typeof PIPELINE_CONFIG;

function getPipelineDisplay(lastEditedBy: string | undefined) {
  if (!lastEditedBy) return null;
  const cfg = PIPELINE_CONFIG[lastEditedBy as PipelineKey];
  if (!cfg) return null;
  return cfg;
}

// ---------------------------------------------------------------------------
// Derive which articles belong to the review queue
// ---------------------------------------------------------------------------

function isAutoGenerated(article: Article): boolean {
  return typeof article.last_edited_by === 'string' && article.last_edited_by.startsWith('auto:');
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface ReviewQueueProps {
  /** All articles (unfiltered) — the component filters internally */
  articles: Article[];
  /** Available categories for display */
  categories: Category[];
  /** Called when the user wants to edit/review an article */
  onEditArticle: (article: Article) => void;
  /** Called after bulk actions so parent can refresh data */
  onRefresh: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ReviewQueue({ articles, categories, onEditArticle, onRefresh }: ReviewQueueProps) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [processing, setProcessing] = useState(false);
  const [filterPipeline, setFilterPipeline] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('draft');

  // ── Derived data ─────────────────────────────────────────────────

  const autoArticles = useMemo(
    () => articles.filter(isAutoGenerated),
    [articles],
  );

  const filteredArticles = useMemo(() => {
    let list = autoArticles;
    if (filterPipeline !== 'all') {
      list = list.filter(a => a.last_edited_by === filterPipeline);
    }
    if (filterStatus !== 'all') {
      list = list.filter(a => a.status === filterStatus);
    }
    // Most recent first
    return list.sort((a, b) => b.created_at.localeCompare(a.created_at));
  }, [autoArticles, filterPipeline, filterStatus]);

  const categoryMap = useMemo(() => {
    const m = new Map<string, Category>();
    for (const c of categories) m.set(c.id, c);
    return m;
  }, [categories]);

  // Pipeline breakdown for stat cards
  const pipelineStats = useMemo(() => {
    const stats: Record<string, { total: number; drafts: number }> = {};
    for (const a of autoArticles) {
      const key = a.last_edited_by || 'unknown';
      if (!stats[key]) stats[key] = { total: 0, drafts: 0 };
      stats[key].total++;
      if (a.status === 'draft') stats[key].drafts++;
    }
    return stats;
  }, [autoArticles]);

  const draftCount = useMemo(
    () => autoArticles.filter(a => a.status === 'draft').length,
    [autoArticles],
  );

  // ── Selection handlers ───────────────────────────────────────────

  const toggleSelect = useCallback((id: string) => {
    setSelected(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const toggleSelectAll = useCallback(() => {
    setSelected(prev => {
      if (prev.size === filteredArticles.length) return new Set();
      return new Set(filteredArticles.map(a => a.id));
    });
  }, [filteredArticles]);

  const clearSelection = useCallback(() => setSelected(new Set()), []);

  // ── Bulk actions ─────────────────────────────────────────────────

  const bulkPublish = useCallback(async () => {
    if (selected.size === 0) return;
    setProcessing(true);
    let successCount = 0;
    const errors: string[] = [];

    for (const id of selected) {
      try {
        await PublicationsAPI.Articles.publishArticle(id, { notify_subscribers: false });
        successCount++;
      } catch (err) {
        errors.push(`Failed to publish article ${id}: ${err instanceof Error ? err.message : 'Unknown error'}`);
      }
    }

    setProcessing(false);
    clearSelection();

    if (successCount > 0) {
      toast.success(`${successCount} article${successCount === 1 ? '' : 's'} published`);
    }
    if (errors.length > 0) {
      toast.error(`${errors.length} article${errors.length === 1 ? '' : 's'} failed to publish`);
      console.error('Bulk publish errors:', errors);
    }
    onRefresh();
  }, [selected, clearSelection, onRefresh]);

  const bulkMoveToReview = useCallback(async () => {
    if (selected.size === 0) return;
    setProcessing(true);
    let successCount = 0;

    for (const id of selected) {
      try {
        await PublicationsAPI.Articles.updateArticle({ id, status: 'in_review' });
        successCount++;
      } catch (err) {
        console.error('Failed to move article to review:', err);
      }
    }

    setProcessing(false);
    clearSelection();
    if (successCount > 0) {
      toast.success(`${successCount} article${successCount === 1 ? '' : 's'} moved to review`);
    }
    onRefresh();
  }, [selected, clearSelection, onRefresh]);

  const bulkDelete = useCallback(async () => {
    if (selected.size === 0) return;
    setProcessing(true);
    let successCount = 0;

    for (const id of selected) {
      try {
        await PublicationsAPI.Articles.deleteArticle(id);
        successCount++;
      } catch (err) {
        console.error('Failed to delete article:', err);
      }
    }

    setProcessing(false);
    clearSelection();
    if (successCount > 0) {
      toast.success(`${successCount} article${successCount === 1 ? '' : 's'} deleted`);
    }
    onRefresh();
  }, [selected, clearSelection, onRefresh]);

  // ── Empty state ──────────────────────────────────────────────────

  if (autoArticles.length === 0) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center justify-center py-16 text-center">
          <div className="h-12 w-12 rounded-full bg-gray-50 flex items-center justify-center mb-4">
            <Inbox className="h-6 w-6 text-gray-400" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-1">No auto-generated articles yet</h3>
          <p className="text-sm text-gray-500 max-w-sm">
            Enable and trigger automation pipelines to populate the review queue.
            Drafts generated by pipelines will appear here for editorial review.
          </p>
        </CardContent>
      </Card>
    );
  }

  // ── Render ───────────────────────────────────────────────────────

  const allSelected = filteredArticles.length > 0 && selected.size === filteredArticles.length;
  const someSelected = selected.size > 0 && selected.size < filteredArticles.length;

  return (
    <div className="space-y-6">
      {/* ── Stat cards ──────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <StatCard
          label="Total Auto-Generated"
          value={autoArticles.length}
          icon={<Zap className="h-4 w-4 text-purple-600" />}
          iconBg="bg-purple-50"
        />
        <StatCard
          label="Awaiting Review"
          value={draftCount}
          icon={<Clock className="h-4 w-4 text-amber-600" />}
          iconBg="bg-amber-50"
          highlight={draftCount > 0}
        />
        <StatCard
          label="Pipelines Active"
          value={Object.keys(pipelineStats).length}
          icon={<Zap className="h-4 w-4 text-blue-600" />}
          iconBg="bg-blue-50"
        />
        <StatCard
          label="Published"
          value={autoArticles.filter(a => a.status === 'published').length}
          icon={<CheckCircle2 className="h-4 w-4 text-green-600" />}
          iconBg="bg-green-50"
        />
      </div>

      {/* ── Toolbar: filters + bulk actions ─────────────────────────── */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-base font-semibold text-gray-900">Review Queue</CardTitle>
            <div className="flex items-center gap-2">
              {/* Pipeline filter */}
              <select
                value={filterPipeline}
                onChange={e => { setFilterPipeline(e.target.value); clearSelection(); }}
                className="text-xs border rounded-md px-2 py-1.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-purple-500"
              >
                <option value="all">All pipelines</option>
                {Object.entries(PIPELINE_CONFIG).map(([key, cfg]) => (
                  <option key={key} value={key}>{cfg.label}</option>
                ))}
              </select>

              {/* Status filter */}
              <select
                value={filterStatus}
                onChange={e => { setFilterStatus(e.target.value); clearSelection(); }}
                className="text-xs border rounded-md px-2 py-1.5 bg-white text-gray-700 focus:outline-none focus:ring-1 focus:ring-purple-500"
              >
                <option value="all">All statuses</option>
                <option value="draft">Drafts</option>
                <option value="in_review">In Review</option>
                <option value="scheduled">Scheduled</option>
                <option value="published">Published</option>
              </select>
            </div>
          </div>

          {/* Bulk action bar — appears when items are selected */}
          {selected.size > 0 && (
            <div className="flex items-center gap-2 mt-3 pt-3 border-t">
              <span className="text-xs font-medium text-gray-600">
                {selected.size} selected
              </span>
              <div className="flex-1" />
              <Button
                size="sm"
                variant="outline"
                className="h-7 text-xs gap-1"
                onClick={bulkMoveToReview}
                disabled={processing}
              >
                <Eye className="h-3 w-3" />
                Move to Review
              </Button>
              <Button
                size="sm"
                className="h-7 text-xs gap-1 bg-green-600 hover:bg-green-700 text-white"
                onClick={bulkPublish}
                disabled={processing}
              >
                {processing ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
                Publish
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="h-7 text-xs gap-1 text-red-600 border-red-200 hover:bg-red-50"
                onClick={bulkDelete}
                disabled={processing}
              >
                <Trash2 className="h-3 w-3" />
                Delete
              </Button>
              <Button
                size="sm"
                variant="ghost"
                className="h-7 text-xs"
                onClick={clearSelection}
              >
                Clear
              </Button>
            </div>
          )}
        </CardHeader>

        <CardContent className="p-0">
          {filteredArticles.length === 0 ? (
            <div className="py-12 text-center text-sm text-gray-500">
              No articles match the selected filters
            </div>
          ) : (
            <div className="divide-y">
              {/* Select-all header */}
              <div className="flex items-center gap-3 px-4 py-2 bg-gray-50/60 text-xs text-gray-500">
                <Checkbox
                  checked={allSelected}
                  // @ts-expect-error — indeterminate mapped to data-state internally
                  data-state={someSelected ? 'indeterminate' : allSelected ? 'checked' : 'unchecked'}
                  onCheckedChange={toggleSelectAll}
                  className="h-3.5 w-3.5"
                />
                <span className="flex-1 font-medium">Article</span>
                <span className="w-24 text-center hidden sm:block">Pipeline</span>
                <span className="w-20 text-center hidden sm:block">Status</span>
                <span className="w-20 text-center hidden md:block">Category</span>
                <span className="w-24 text-right hidden lg:block">Created</span>
                <span className="w-16" />
              </div>

              {filteredArticles.map(article => (
                <ReviewRow
                  key={article.id}
                  article={article}
                  isSelected={selected.has(article.id)}
                  onToggle={() => toggleSelect(article.id)}
                  onEdit={() => onEditArticle(article)}
                  category={categoryMap.get(article.category_id)}
                />
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function StatCard({
  label,
  value,
  icon,
  iconBg,
  highlight,
}: {
  label: string;
  value: number;
  icon: React.ReactNode;
  iconBg: string;
  highlight?: boolean;
}) {
  return (
    <Card className={cn('transition-colors', highlight && 'border-amber-300 bg-amber-50/30')}>
      <CardContent className="p-4 flex items-center gap-3">
        <div className={cn('h-9 w-9 rounded-lg flex items-center justify-center shrink-0', iconBg)}>
          {icon}
        </div>
        <div className="min-w-0">
          <p className="text-2xl font-bold text-gray-900 leading-none">{value}</p>
          <p className="text-xs text-gray-500 mt-0.5 truncate">{label}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function ReviewRow({
  article,
  isSelected,
  onToggle,
  onEdit,
  category,
}: {
  article: Article;
  isSelected: boolean;
  onToggle: () => void;
  onEdit: () => void;
  category?: Category;
}) {
  const pipeline = getPipelineDisplay(article.last_edited_by);
  const PipelineIcon = pipeline?.icon || Zap;
  const hasImage = !!(article.hero_image_url || article.featured_image);

  return (
    <div
      className={cn(
        'flex items-center gap-3 px-4 py-3 hover:bg-gray-50/60 transition-colors group',
        isSelected && 'bg-purple-50/40',
      )}
    >
      <Checkbox
        checked={isSelected}
        onCheckedChange={onToggle}
        className="h-3.5 w-3.5"
      />

      {/* Article info */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <p className="text-sm font-medium text-gray-900 truncate">{article.title}</p>
          {hasImage && (
            <ImageIcon className="h-3 w-3 text-gray-400 shrink-0" />
          )}
        </div>
        <p className="text-xs text-gray-500 truncate mt-0.5">
          {truncateText(article.excerpt || '', 100)}
        </p>
      </div>

      {/* Pipeline badge */}
      <div className="w-24 hidden sm:flex justify-center">
        {pipeline ? (
          <Badge variant="outline" className={cn('text-[10px] px-1.5 py-0 h-5 gap-1 border', pipeline.badgeClass)}>
            <PipelineIcon className="h-3 w-3" />
            {pipeline.shortLabel}
          </Badge>
        ) : (
          <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-5 text-gray-500">
            Unknown
          </Badge>
        )}
      </div>

      {/* Status */}
      <div className="w-20 hidden sm:flex justify-center">
        <StatusBadge status={article.status} className="text-[10px] px-1.5 py-0 h-5" />
      </div>

      {/* Category */}
      <div className="w-20 hidden md:flex justify-center">
        {category ? (
          <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-5 gap-1 max-w-full truncate">
            <FolderOpen className="h-3 w-3 shrink-0" />
            <span className="truncate">{category.name}</span>
          </Badge>
        ) : (
          <span className="text-[10px] text-gray-400 italic">None</span>
        )}
      </div>

      {/* Created */}
      <div className="w-24 hidden lg:block text-right">
        <p className="text-[11px] text-gray-500">{getRelativeTime(article.created_at)}</p>
      </div>

      {/* Actions */}
      <div className="w-16 flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <Button
          size="sm"
          variant="ghost"
          className="h-7 w-7 p-0"
          onClick={onEdit}
          title="Review & Edit"
        >
          <Edit className="h-3.5 w-3.5 text-gray-500" />
        </Button>
      </div>
    </div>
  );
}
