// Domain Types
import type { BaseClient } from '../../../../shared/types';

/** What the compose wizard can send through. */
export type CommunicationChannel = 'email' | 'whatsapp';

/**
 * What a HISTORY row can be. Adds `portal`, which the wizard cannot produce:
 * it is what an individual message becomes when the adviser leaves "Send
 * Email" unchecked on a client profile. The portal copy is always written, so
 * the message is real — no provider was involved. Kept separate from
 * `CommunicationChannel` so the wizard's own types stay honest about the two
 * channels it can actually send on.
 */
export type HistoryChannel = CommunicationChannel | 'portal';

/**
 * Delivery status shown in the Communication Centre.
 *
 * `sent` is a legacy value still present on older stored rows; new sends write
 * one of the others. `partial` and `rejected` exist because the send pipeline
 * used to report 'completed' unconditionally — a run where the provider refused
 * every address was indistinguishable from one that landed.
 */
export type CommunicationStatus =
  | 'draft'
  | 'scheduled'
  | 'sending'
  | 'sent'
  | 'completed'
  | 'partial'
  | 'failed'
  | 'rejected';

/** Status values offered in the history filter, in reporting order. */
export const COMMUNICATION_STATUS_FILTERS: ReadonlyArray<{
  value: CommunicationStatus;
  label: string;
}> = [
  { value: 'completed', label: 'Completed' },
  { value: 'partial', label: 'Partially delivered' },
  { value: 'failed', label: 'Failed' },
  { value: 'rejected', label: 'Rejected' },
  { value: 'sending', label: 'Sending' },
  { value: 'scheduled', label: 'Scheduled' },
  { value: 'draft', label: 'Draft' },
];
export type RecipientType = 'single' | 'multiple' | 'group';
export type GroupType = 'system' | 'custom';
export type SchedulingType = 'immediate' | 'scheduled';
export type RecurringFrequency =
  | 'daily'
  | 'weekly'
  | 'monthly'
  | 'quarterly'
  | 'annually'
  | 'custom';
export type EndConditionType = 'never' | 'after_occurrences' | 'on_date';

// Client Types
// Extends BaseClient (§9.2). `surname` kept for backward compat with existing templates.
export interface Client extends BaseClient {
  surname: string;
  status?: string;
  category?: string;
  advisorId?: string;
  lastContacted?: Date;
  hasEmailOptIn: boolean;
  hasWhatsAppOptIn: boolean;
}

// Group Types
export interface GroupFilterConfig {
  productFilters?: {
    provider?: string;
    type?: string;
  }[];
  netWorthFilters?: {
    min?: number;
    max?: number;
  }[];
  ageFilters?: {
    min?: number;
    max?: number;
  }[];
  maritalStatusFilters?: string[];
  employmentStatusFilters?: string[];
  genderFilters?: string[];
  countryFilters?: string[];
  incomeFilters?: {
    min?: number;
    max?: number;
  }[];
  occupationFilters?: string[];
  dependantCountFilters?: {
    min?: number;
    max?: number;
  }[];
  retirementAgeFilters?: {
    min?: number;
    max?: number;
  }[];
  hasAssetsFilter?: boolean;
  hasLiabilitiesFilter?: boolean;
}

export interface ExternalContact {
  email: string;
  name?: string;
  source: string;
  subscribedAt: string;
}

export interface ClientGroup {
  id: string;
  name: string;
  description: string;
  color?: string;
  type: GroupType;
  clientIds: string[];
  externalContacts?: ExternalContact[];
  filterConfig?: GroupFilterConfig;
  clientCount: number;
  /** True for system groups maintained automatically (e.g. provider groups). */
  autoGenerated?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  criteria?: Record<string, unknown>;
}

// Template Types
export interface EmailTemplate {
  id: string;
  name: string;
  enabled: boolean;
  subject: string;
  title: string;
  subtitle: string;
  greeting: string;
  bodyHtml: string;
  buttonLabel: string;
  buttonUrl: string;
  footerNote: string;
  category?: string;
  createdAt?: string;
  isSystem?: boolean; // Merged from simpler type
}

export interface EmailFooterSettings {
  companyName: string;
  address: string;
  contactEmail: string;
  contactPhone: string;
  socialLinks: {
    linkedin?: string;
    instagram?: string;
    youtube?: string;
    facebook?: string;
    twitter?: string;
  };
  copyrightText: string;
}

// File/Attachment Types
export interface AttachmentFile {
  id: string;
  name: string;
  path: string;
  size: number;
  type: string;
  url?: string;
}

// Scheduling Types
export interface SchedulingConfig {
  type: SchedulingType;
  startDate?: Date;
  time?: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  customInterval?: number;
  endCondition?: EndConditionType;
  endOccurrences?: number;
  endDate?: Date;
}

// Draft/Campaign Types
export interface CommunicationDraft {
  id?: string;
  step: number;
  channel: CommunicationChannel;
  recipientType: RecipientType;
  selectedRecipients: Client[];
  selectedGroup?: ClientGroup;
  subject: string;
  title?: string;
  bodyHtml: string;
  attachments: AttachmentFile[];
  scheduling: SchedulingConfig;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface CommunicationPayload {
  channel: CommunicationChannel;
  recipient_ids: string[];
  group_id?: string;
  subject?: string;
  title?: string;
  body_html?: string;
  attachments: AttachmentFile[];
  scheduling: SchedulingConfig;
}

export interface CommunicationCampaign {
  id: string;
  name: string;
  subject: string;
  status: string;
  sentAt?: string;
  stats?: {
    sent: number;
    opened: number;
    clicked: number;
  };
}

export interface BackendCampaign {
  id: string;
  subject: string;
  bodyHtml: string;
  channel: HistoryChannel;
  recipientType: RecipientType;
  selectedRecipients: Array<{ id: string; email?: string; name?: string; [key: string]: unknown }>;
  selectedGroup?: {
    id: string;
    name: string;
    type?: string;
    clientCount?: number;
    [key: string]: unknown;
  };
  status: CommunicationStatus;
  attachments?: Array<{ id: string; name: string; path: string; type: string; size: number }>;
  stats?: { sent: number; failed: number; total: number };
  /** `direct` rows are individual messages sent from a client profile. */
  origin?: 'campaign' | 'direct';
  cc?: string[];
  failureReason?: string;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  createdByName?: string;
}

// Log/History Types
export interface CommunicationLog {
  id: string;
  subject: string;
  category: string;
  created_at: string;
  read: boolean;
  sender_name?: string;
  body?: string;
  content?: string;
  /** True only when the email provider ACCEPTED the message. */
  sent_via_email: boolean;
  /** Per-message email outcome; absent on rows written before it was tracked. */
  email_status?: 'sent' | 'failed' | 'rejected' | 'skipped';
  email_error?: string;
  /** Addresses copied on the email. */
  cc?: string[];
  attachments?: AttachmentFile[];
}

/** Paginated communication history from GET /communication/campaigns */
export interface CampaignHistorySenderOption {
  userId: string;
  label: string;
}

export interface CampaignHistoryPageResult {
  entries: ActivityLogEntry[];
  total: number;
  page: number;
  limit: number;
  senderOptions: CampaignHistorySenderOption[];
}

export interface ActivityLogEntry {
  id: string;
  timestamp: Date;
  userId: string;
  userName: string;
  channel: HistoryChannel;
  recipientType: RecipientType;
  recipientCount: number;
  /** Group name when recipientType is `group` (from campaign.selectedGroup). */
  groupName?: string;
  subject?: string;
  messagePreview: string;
  /** Longer plain-text body preview for detail panel. */
  messagePreviewFull?: string;
  attachmentCount: number;
  templateUsed?: string;
  status: CommunicationStatus;
  /** Individual client message vs Communication Centre campaign. */
  origin: 'campaign' | 'direct';
  /** Delivery counts, when the send has actually run. */
  stats?: { sent: number; failed: number; total: number };
  /** CC'd addresses on the envelope. */
  cc?: string[];
  /** Why the send did not fully complete. */
  failureReason?: string;
}

export interface CommunicationMessage {
  id: string;
  subject: string;
  content: string;
  from: string;
  receivedAt: string;
  isRead: boolean;
}

// Request/Response Types
export interface MessageCreate {
  recipients: string[];
  subject: string;
  content: string;
  category?: string;
  priority?: string;
  senderName?: string;
  sendEmail?: boolean;
  recipientEmail?: string;
  attachments?: AttachmentFile[];
  cc?: string[];
}

export interface SendMessageResponse {
  success: boolean;
  messageId: string;
  status?: 'completed' | 'partial' | 'failed' | 'rejected';
  stats?: { sent: number; failed: number; total: number };
  /** CC addresses that made it onto the envelope. */
  cc?: string[];
  /** Set when some CC entries were unusable and were dropped from the send. */
  ccWarning?: string;
  failureReason?: string;
}

export interface SendCampaignResponse {
  success: boolean;
  sent: number;
  status?: CommunicationStatus;
}

export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  eligibleRecipients: Client[];
  ineligibleRecipients: Array<{ client: Client; reason: string }>;
}
