/**
 * Assets tab — pure model helpers (Guidelines §7.1: derived display state
 * lives outside the components so it can be tested without rendering).
 */

import type {
  SocialAsset,
  SocialAssetState,
  SocialAutomationSettings,
  SocialAutomationSettingsPatch,
  SocialBatchStatus,
  SocialChannel,
  SocialImageStatus,
} from './assetsTypes';

export const CHANNEL_ORDER: SocialChannel[] = ['linkedin', 'instagram', 'x'];

export const CHANNEL_LABEL: Record<SocialChannel, string> = {
  linkedin: 'LinkedIn',
  instagram: 'Instagram',
  x: 'X',
};

export interface StatusDisplay {
  label: string;
  /** Tailwind classes following the §8.3 status colour vocabulary. */
  className: string;
  description: string;
}

/** green = live/success, blue = informational, purple = system action, amber = suspended, red = error */
export const ASSET_STATE_DISPLAY: Record<SocialAssetState, StatusDisplay> = {
  generated: {
    label: 'Candidate',
    className: 'bg-blue-50 text-blue-700 border-blue-200',
    description: 'Generated by the routine; available for selection.',
  },
  shortlisted: {
    label: 'Shortlisted',
    className: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'Marked as a strong option by the routine.',
  },
  selected: {
    label: 'Selected',
    className: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'Chosen for this week; being sent to Buffer.',
  },
  scheduled: {
    label: 'Scheduled',
    className: 'bg-green-50 text-green-700 border-green-200',
    description: 'In Buffer’s queue with a publish time.',
  },
  published: {
    label: 'Published',
    className: 'bg-green-100 text-green-800 border-green-300',
    description: 'Buffer has published it.',
  },
  failed: {
    label: 'Failed',
    className: 'bg-red-50 text-red-700 border-red-200',
    description: 'Buffer or the scheduler reported an error.',
  },
  rejected: {
    label: 'Removed',
    className: 'bg-amber-50 text-amber-700 border-amber-200',
    description: 'Removed from the candidates by an admin.',
  },
  expired: {
    label: 'Expired',
    className: 'bg-gray-100 text-gray-600 border-gray-200',
    description: 'The week has passed without this asset being used.',
  },
};

export const IMAGE_STATUS_DISPLAY: Record<SocialImageStatus, StatusDisplay> = {
  none: {
    label: 'No image',
    className: 'bg-gray-100 text-gray-600 border-gray-200',
    description: 'Text-only asset.',
  },
  pending: {
    label: 'Image queued',
    className: 'bg-blue-50 text-blue-700 border-blue-200',
    description: 'Waiting for the hourly render job.',
  },
  rendering: {
    label: 'Rendering',
    className: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'Being generated now.',
  },
  ready: {
    label: 'Image ready',
    className: 'bg-green-50 text-green-700 border-green-200',
    description: 'Stored in the public bucket.',
  },
  failed: {
    label: 'Image failed',
    className: 'bg-red-50 text-red-700 border-red-200',
    description: 'Rendering failed; retry from the card.',
  },
};

export const BATCH_STATUS_DISPLAY: Record<SocialBatchStatus, StatusDisplay> = {
  generating: {
    label: 'Generating',
    className: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'The generation routine is running or stopped early.',
  },
  generated: {
    label: 'Generated',
    className: 'bg-blue-50 text-blue-700 border-blue-200',
    description: 'Candidates ready; awaiting the scheduling routine.',
  },
  selecting: {
    label: 'Selecting',
    className: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'The scheduling routine is choosing posts.',
  },
  scheduled: {
    label: 'Scheduled',
    className: 'bg-green-50 text-green-700 border-green-200',
    description: 'Posts are queued in Buffer.',
  },
  failed: {
    label: 'Failed',
    className: 'bg-red-50 text-red-700 border-red-200',
    description: 'Nothing could be scheduled — read the run report.',
  },
  cancelled: {
    label: 'Cancelled',
    className: 'bg-amber-50 text-amber-700 border-amber-200',
    description: 'Cancelled by an admin.',
  },
};

/** States an admin may remove from the candidate pool. */
export const REJECTABLE_STATES: SocialAssetState[] = [
  'generated',
  'shortlisted',
  'selected',
  'failed',
];

const STATE_ORDER: Record<SocialAssetState, number> = {
  published: 0,
  scheduled: 1,
  selected: 2,
  shortlisted: 3,
  generated: 4,
  failed: 5,
  rejected: 6,
  expired: 7,
};

/** Sort: live things first (by rank), then candidates in creation order, then the removed. */
export function sortAssets(assets: SocialAsset[]): SocialAsset[] {
  return [...assets].sort((a, b) => {
    const order = STATE_ORDER[a.state] - STATE_ORDER[b.state];
    if (order !== 0) return order;
    const rank = (a.selection_rank ?? 99) - (b.selection_rank ?? 99);
    if (rank !== 0) return rank;
    return a.created_at.localeCompare(b.created_at);
  });
}

export function groupAssetsByChannel(assets: SocialAsset[]): Record<SocialChannel, SocialAsset[]> {
  const groups: Record<SocialChannel, SocialAsset[]> = { linkedin: [], instagram: [], x: [] };
  for (const asset of assets) {
    if (asset.channel in groups) groups[asset.channel].push(asset);
  }
  for (const channel of CHANNEL_ORDER) groups[channel] = sortAssets(groups[channel]);
  return groups;
}

export interface ChannelCounts {
  total: number;
  candidates: number;
  live: number; // selected + scheduled + published
  published: number;
}

export function countChannel(assets: SocialAsset[]): ChannelCounts {
  return assets.reduce<ChannelCounts>(
    (acc, a) => {
      acc.total += 1;
      if (a.state === 'generated' || a.state === 'shortlisted') acc.candidates += 1;
      if (a.state === 'selected' || a.state === 'scheduled' || a.state === 'published')
        acc.live += 1;
      if (a.state === 'published') acc.published += 1;
      return acc;
    },
    { total: 0, candidates: 0, live: 0, published: 0 },
  );
}

// ---------------------------------------------------------------------------
// ISO weeks — the batch key vocabulary the routines use ("2026-W38")
// ---------------------------------------------------------------------------

const DAY_MS = 24 * 60 * 60 * 1000;

function isoDow(date: Date): number {
  const dow = date.getUTCDay();
  return dow === 0 ? 7 : dow;
}

/** Monday 00:00 UTC of ISO week 1 of `year`: the week containing 4 January. */
function mondayOfWeekOne(year: number): Date {
  const jan4 = new Date(Date.UTC(year, 0, 4));
  return new Date(jan4.getTime() - (isoDow(jan4) - 1) * DAY_MS);
}

/** `YYYY-Www` for the ISO week containing `date` (evaluated on the calendar date, UTC). */
export function isoWeekKey(date: Date): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const thursday = new Date(d.getTime() + (4 - isoDow(d)) * DAY_MS);
  const year = thursday.getUTCFullYear();
  const week =
    Math.round((thursday.getTime() - mondayOfWeekOne(year).getTime()) / (7 * DAY_MS)) + 1;
  return `${year}-W${String(week).padStart(2, '0')}`;
}

/**
 * The week the routines are working FOR, by the same rule the playbooks use:
 * on Saturday/Sunday that is next week, otherwise the current week.
 */
export function postingWeekKey(now = new Date()): string {
  const local = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const dow = local.getDay() === 0 ? 7 : local.getDay();
  const target = dow >= 6 ? new Date(local.getTime() + 7 * DAY_MS) : local;
  return isoWeekKey(target);
}

export function parseWeekKey(weekKey: string): { year: number; week: number } | null {
  const match = /^(\d{4})-W(\d{2})$/.exec(weekKey);
  if (!match) return null;
  return { year: Number(match[1]), week: Number(match[2]) };
}

/** Monday and Sunday (UTC midnight) of an ISO week. */
export function isoWeekRange(weekKey: string): { start: Date; end: Date } | null {
  const parsed = parseWeekKey(weekKey);
  if (!parsed) return null;
  const start = new Date(mondayOfWeekOne(parsed.year).getTime() + (parsed.week - 1) * 7 * DAY_MS);
  const end = new Date(start.getTime() + 6 * DAY_MS);
  return { start, end };
}

/** "Week 38 · 14 – 20 Sep 2026" */
export function formatWeekLabel(weekKey: string): string {
  const range = isoWeekRange(weekKey);
  const parsed = parseWeekKey(weekKey);
  if (!range || !parsed) return weekKey;
  const day = (d: Date) => d.toLocaleDateString('en-ZA', { day: '2-digit', timeZone: 'UTC' });
  const monthYear = (d: Date) =>
    d.toLocaleDateString('en-ZA', { month: 'short', year: 'numeric', timeZone: 'UTC' });
  const sameMonth = range.start.getUTCMonth() === range.end.getUTCMonth();
  const span = sameMonth
    ? `${day(range.start)} – ${day(range.end)} ${monthYear(range.end)}`
    : `${day(range.start)} ${range.start.toLocaleDateString('en-ZA', { month: 'short', timeZone: 'UTC' })} – ${day(range.end)} ${monthYear(range.end)}`;
  return `Week ${parsed.week} · ${span}`;
}

/** "Tue 15 Sep, 07:30" in the posting timezone (en-ZA, §8.3). */
export function formatSlot(iso: string | null | undefined, timeZone: string): string {
  if (!iso) return '—';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '—';
  try {
    return `${date.toLocaleDateString('en-ZA', { weekday: 'short', day: '2-digit', month: 'short', timeZone })}, ${date.toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone })}`;
  } catch {
    return date.toISOString();
  }
}

// ---------------------------------------------------------------------------
// Preferred slots — "dow HH:MM" lines in the settings dialog
// ---------------------------------------------------------------------------

export const SLOT_RE = /^(mon|tue|wed|thu|fri|sat|sun)\s+([01]?\d|2[0-3]):[0-5]\d$/i;

export function slotsToText(slots: string[] | undefined): string {
  return (slots ?? []).join('\n');
}

/** Returns the parsed slots, or the first invalid line. */
export function parseSlotsText(text: string): { slots: string[]; invalid: string | null } {
  const lines = text
    .split(/\r?\n|,/)
    .map((l) => l.trim().toLowerCase())
    .filter(Boolean);
  for (const line of lines) {
    if (!SLOT_RE.test(line)) return { slots: [], invalid: line };
  }
  return { slots: lines, invalid: null };
}

/** Pull the human-readable highlights out of a batch's run report. */
export function summarizeRunReport(report: Record<string, unknown> | null | undefined): string[] {
  if (!report) return [];
  const lines: string[] = [];
  const generation = report.generation as Record<string, unknown> | undefined;
  const selection = report.selection as Record<string, unknown> | undefined;
  if (generation) {
    const used = generation.articles_used ?? generation.articlesUsed;
    const considered = generation.articles_considered ?? generation.articlesConsidered;
    if (used !== undefined || considered !== undefined) {
      lines.push(`Articles: ${used ?? '?'} used of ${considered ?? '?'} considered`);
    }
    if (typeof generation.notes === 'string' && generation.notes)
      lines.push(`Generation: ${generation.notes}`);
  }
  if (selection) {
    const scheduled = selection.scheduled as Record<string, number> | undefined;
    if (scheduled && typeof scheduled === 'object') {
      const parts = Object.entries(scheduled).map(
        ([c, n]) => `${CHANNEL_LABEL[c as SocialChannel] ?? c} ${n}`,
      );
      if (parts.length) lines.push(`Scheduled: ${parts.join(', ')}`);
    }
    const skipped = selection.skipped as Record<string, string> | undefined;
    if (skipped && typeof skipped === 'object') {
      for (const [c, reason] of Object.entries(skipped)) {
        lines.push(`Skipped ${CHANNEL_LABEL[c as SocialChannel] ?? c}: ${reason}`);
      }
    }
    const failures = selection.failures as string[] | undefined;
    if (Array.isArray(failures) && failures.length) lines.push(`Failures: ${failures.join('; ')}`);
    if (typeof selection.context_notes === 'string' && selection.context_notes) {
      lines.push(`Context: ${selection.context_notes}`);
    }
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Settings dialog form <-> API patch
// ---------------------------------------------------------------------------

export interface SettingsFormState {
  enabled: boolean;
  assets_per_channel: string;
  posts_per_channel_per_week: string;
  channels: SocialChannel[];
  posting_timezone: string;
  site_origin: string;
  slots: Record<SocialChannel, string>;
  style_guide: string;
  compliance_rules: string;
}

export function settingsToForm(settings?: SocialAutomationSettings): SettingsFormState {
  return {
    enabled: settings?.enabled ?? true,
    assets_per_channel: String(settings?.assets_per_channel ?? 5),
    posts_per_channel_per_week: String(settings?.posts_per_channel_per_week ?? 2),
    channels: settings?.channels ?? [...CHANNEL_ORDER],
    posting_timezone: settings?.posting_timezone ?? 'Africa/Johannesburg',
    site_origin: settings?.site_origin ?? '',
    slots: {
      linkedin: slotsToText(settings?.preferred_slots?.linkedin),
      instagram: slotsToText(settings?.preferred_slots?.instagram),
      x: slotsToText(settings?.preferred_slots?.x),
    },
    style_guide: settings?.style_guide ?? '',
    compliance_rules: settings?.compliance_rules ?? '',
  };
}

/** Validate and translate the form into the API patch, or explain what is wrong. */
export function formToPatch(form: SettingsFormState): {
  patch?: SocialAutomationSettingsPatch;
  error?: string;
} {
  const assetsPerChannel = Number(form.assets_per_channel);
  const postsPerWeek = Number(form.posts_per_channel_per_week);
  if (!Number.isInteger(assetsPerChannel) || assetsPerChannel < 1 || assetsPerChannel > 20) {
    return { error: 'Assets per channel must be a whole number between 1 and 20.' };
  }
  if (!Number.isInteger(postsPerWeek) || postsPerWeek < 0 || postsPerWeek > 7) {
    return { error: 'Posts per channel per week must be a whole number between 0 and 7.' };
  }
  if (form.channels.length === 0) return { error: 'Choose at least one channel.' };
  if (!/^https?:\/\/.+/.test(form.site_origin.trim())) {
    return { error: 'Site origin must be a full URL, e.g. https://www.navigatewealth.co' };
  }
  const preferred_slots: Record<string, string[]> = {};
  for (const channel of CHANNEL_ORDER) {
    const { slots, invalid } = parseSlotsText(form.slots[channel]);
    if (invalid) {
      return {
        error: `${CHANNEL_LABEL[channel]} slot "${invalid}" is not "dow HH:MM" (e.g. tue 07:30).`,
      };
    }
    preferred_slots[channel] = slots;
  }
  return {
    patch: {
      enabled: form.enabled,
      assets_per_channel: assetsPerChannel,
      posts_per_channel_per_week: postsPerWeek,
      channels: form.channels,
      posting_timezone: form.posting_timezone.trim(),
      site_origin: form.site_origin.trim(),
      preferred_slots,
      style_guide: form.style_guide,
      compliance_rules: form.compliance_rules,
    },
  };
}
