import { User, MapPin, Briefcase, FileText, Shield, LucideIcon } from 'lucide-react';

export const STEPS: { number: number; title: string; subtitle: string; icon: LucideIcon }[] = [
  { number: 1, title: 'Personal', subtitle: 'Tell us about yourself', icon: User },
  { number: 2, title: 'Contact', subtitle: 'How can we reach you?', icon: MapPin },
  { number: 3, title: 'Employment', subtitle: 'Your professional background', icon: Briefcase },
  { number: 4, title: 'Services', subtitle: 'What brings you to Navigate Wealth?', icon: FileText },
  { number: 5, title: 'Terms', subtitle: 'Review and confirm', icon: Shield },
];

export const TITLES = ['Mr', 'Mrs', 'Ms', 'Miss', 'Dr', 'Prof'];

export const GENDERS = ['Male', 'Female', 'Other', 'Prefer not to say'];

export const MARITAL_STATUSES = ['Single', 'Married', 'Divorced', 'Widowed', 'Life Partner'];

export const MARITAL_REGIMES = [
  'In Community of Property',
  'Out of Community of Property (with accrual)',
  'Out of Community of Property (without accrual)',
];

export const PROVINCES = [
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'Northern Cape',
  'North West',
  'Western Cape',
];

export const PREFERRED_CONTACT_METHODS = ['Email', 'Phone Call', 'WhatsApp', 'SMS'];

export const BEST_TIMES_TO_CONTACT = ['Morning (8am–12pm)', 'Afternoon (12pm–5pm)', 'Evening (5pm–8pm)', 'No preference'];

export const INDUSTRIES = [
  'Accounting & Auditing',
  'Advertising & Marketing',
  'Aerospace & Defence',
  'Agriculture & Farming',
  'Architecture & Design',
  'Arts & Culture',
  'Automotive',
  'Aviation',
  'Banking',
  'Biotechnology',
  'Broadcasting & Media',
  'Chemical & Petrochemical',
  'Civil Engineering',
  'Cleaning & Facilities Management',
  'Community & Social Services',
  'Construction & Infrastructure',
  'Consulting & Advisory',
  'Consumer Goods & FMCG',
  'Customs & Freight',
  'Dental & Oral Health',
  'E-Commerce',
  'Education & Training',
  'Electrical Engineering',
  'Electronics & Semiconductors',
  'Energy & Utilities',
  'Engineering (General)',
  'Entertainment & Events',
  'Environmental Services',
  'Fashion & Apparel',
  'Film & Television',
  'Financial Services',
  'Fintech',
  'Fishing & Marine',
  'Food & Beverage',
  'Forestry & Paper',
  'Funeral Services',
  'Gaming & Esports',
  'Government & Public Sector',
  'Healthcare & Medical',
  'Hospitality & Hotels',
  'Human Resources & Recruitment',
  'Import & Export',
  'Information Technology',
  'Insurance',
  'Interior Design',
  'Investment Management',
  'Journalism & Publishing',
  'Legal Services',
  'Logistics & Supply Chain',
  'Manufacturing',
  'Maritime & Shipping',
  'Mechanical Engineering',
  'Media & Communications',
  'Medical Devices',
  'Mining & Resources',
  'Motor Industry',
  'Music & Recording',
  'Non-Profit & NGO',
  'Oil & Gas',
  'Optometry & Optical',
  'Packaging',
  'Pharmaceuticals',
  'Photography & Videography',
  'Plastics & Rubber',
  'Printing & Signage',
  'Private Equity & Venture Capital',
  'Private Security',
  'Professional Services',
  'Property & Real Estate',
  'Psychology & Counselling',
  'Public Relations',
  'Publishing',
  'Rail & Transport',
  'Religion & Faith-Based',
  'Renewable Energy',
  'Research & Development',
  'Restaurant & Food Service',
  'Retail',
  'Safety & Compliance',
  'Science & Laboratory',
  'Social Media & Digital',
  'Software Development',
  'Sport & Recreation',
  'Steel & Metals',
  'Stockbroking & Trading',
  'Telecommunications',
  'Textiles',
  'Tourism & Travel',
  'Trading & Distribution',
  'Transport & Logistics',
  'Veterinary Services',
  'Warehousing & Storage',
  'Waste Management & Recycling',
  'Water & Sanitation',
  'Wealth Management',
  'Wholesale',
  'Wine & Spirits',
  'Other',
];

export const INCOME_RANGES = [
  'Prefer not to say',
  'Under R15,000',
  'R15,000 – R30,000',
  'R30,000 – R50,000',
  'R50,000 – R80,000',
  'R80,000 – R120,000',
  'R120,000 – R200,000',
  'R200,000+',
];

export const EXPENSE_RANGES = [
  'Prefer not to say',
  'Under R10,000',
  'R10,000 – R20,000',
  'R20,000 – R40,000',
  'R40,000 – R60,000',
  'R60,000 – R100,000',
  'R100,000+',
];

export const ACCOUNT_REASON_OPTIONS = [
  'Investment Management',
  'Life Assurance',
  'Medical Aid',
  'Estate Planning',
  'Retirement Planning',
  'Tax Planning',
  'Risk Management',
  'Financial Planning',
  'Employee Benefits',
  'Other',
];

export const URGENCY_OPTIONS = [
  { value: 'immediately', label: 'Immediately', description: 'I need to get started right away' },
  { value: 'within_1_month', label: 'Within 1 month', description: 'I\'d like to begin soon' },
  { value: 'within_3_months', label: 'Within 3 months', description: 'I\'m planning ahead' },
  { value: 'exploring', label: 'Just exploring', description: 'I want to understand my options' },
];

export const EXISTING_PRODUCTS = [
  'Retirement Annuity',
  'Pension / Provident Fund',
  'Life Insurance',
  'Disability Cover',
  'Medical Aid',
  'Unit Trust',
  'Endowment',
  'Tax-Free Savings Account',
  'Offshore Investment',
  'Estate Planning',
  'Short-term Insurance',
  'None of the above',
];

export const INITIAL_DATA = {
  title: '',
  firstName: '',
  middleName: '',
  preferredName: '',
  lastName: '',
  dateOfBirth: '',
  gender: '',
  nationality: 'South African',
  idType: '' as '' | 'sa_id' | 'passport',
  idNumber: '',
  taxNumber: '',
  isSATaxResident: null as boolean | null,
  maritalStatus: '',
  maritalRegime: '',
  numberOfDependants: '',
  spouseFirstName: '',
  spouseLastName: '',
  spouseDateOfBirth: '',
  spouseEmployed: '',
  emailAddress: '',
  alternativeEmail: '',
  cellphoneNumber: '',
  alternativeCellphone: '',
  whatsappNumber: '',
  preferredContactMethod: '',
  bestTimeToContact: '',
  residentialAddressLine1: '',
  residentialAddressLine2: '',
  residentialSuburb: '',
  residentialCity: '',
  residentialProvince: '',
  residentialPostalCode: '',
  residentialCountry: 'South Africa',
  employmentStatus: '',
  jobTitle: '',
  employerName: '',
  industry: '',
  industryOther: '',
  selfEmployedCompanyName: '',
  selfEmployedIndustry: '',
  selfEmployedIndustryOther: '',
  selfEmployedDescription: '',
  grossMonthlyIncome: '',
  monthlyExpensesEstimate: '',
  accountReasons: [] as string[],
  otherReason: '',
  financialGoals: '',
  urgency: '',
  existingProducts: [] as string[],
  existingProductProviders: {} as Record<string, string>,
  referralSource: '',
  referralName: '',
  termsAccepted: false,
  popiaConsent: false,
  disclosureAcknowledged: false,
  faisAcknowledged: false,
  electronicCommunicationConsent: false,
  communicationConsent: false,
  signatureFullName: '',
};