/* AUTOGENERATED FILE - FALLBACK VALUES ONLY */

const fallbackProjectId = "vpjmdsltwrnpefzcgdmz";
const fallbackPublicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwam1kc2x0d3JucGVmemNnZG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNDcxNjUsImV4cCI6MjA3NTkyMzE2NX0.JeGS_wxI-iw6Tz2fTIwRMBT59oUEf0g1Q0ySvwhdSRg";

const env = import.meta.env as {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PROJECT_ID?: string;
  VITE_SUPABASE_ANON_KEY?: string;
};

function projectIdFromUrl(value?: string): string | undefined {
  if (!value) return undefined;

  try {
    const hostname = new URL(value).hostname;
    const match = hostname.match(/^([a-z0-9-]+)\.supabase\.co$/i);
    return match?.[1];
  } catch {
    return undefined;
  }

  return undefined;
}

export const projectId =
  env.VITE_SUPABASE_PROJECT_ID ||
  projectIdFromUrl(env.VITE_SUPABASE_URL) ||
  fallbackProjectId;

export const publicAnonKey = env.VITE_SUPABASE_ANON_KEY || fallbackPublicAnonKey;
export const supabaseUrl = env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
