import * as kv from './kv_store.tsx';
import type { GenerateArticleResult } from './publications-ai-service.ts';
import { createModuleLogger } from './stderr-logger.ts';
import type { ContentSource, PipelineId } from './auto-content-types.ts';

const log = createModuleLogger('auto-content');

// ---------------------------------------------------------------------------
// KV Key Helpers
// ---------------------------------------------------------------------------

export const CONFIG_PREFIX = 'auto_content:config:';
export const RUN_PREFIX = 'auto_content:run:';
export const CALENDAR_PREFIX = 'auto_content:calendar_event:';
export const PROCESSED_PREFIX = 'auto_content:processed:';
export const SOURCE_PREFIX = 'auto_content:source:';

export function configKey(id: PipelineId): string {
  return `${CONFIG_PREFIX}${id}`;
}
export function runKey(id: PipelineId, ts: string): string {
  return `${RUN_PREFIX}${id}:${ts}`;
}
export function calendarKey(id: string): string {
  return `${CALENDAR_PREFIX}${id}`;
}
export function processedKey(pipeline: PipelineId, hash: string): string {
  return `${PROCESSED_PREFIX}${pipeline}:${hash}`;
}
export function sourceKey(id: string): string {
  return `${SOURCE_PREFIX}${id}`;
}

// Cross-pipeline dedup prefix — prevents multiple pipelines covering the same topic
export const GLOBAL_TOPIC_PREFIX = 'auto_content:global_topic:';
// Recently used Unsplash photo IDs — prevents repetitive hero images
export const USED_IMAGE_PREFIX = 'auto_content:used_image:';

// ---------------------------------------------------------------------------
// Default Feed URL Constants
// ---------------------------------------------------------------------------

export const MARKET_RSS_FEEDS = [
  'https://www.investing.com/rss/news_14.rss', // Economic news
  'https://www.investing.com/rss/news_25.rss', // Stock market
];

export const REGULATORY_RSS_FEEDS = [
  'https://www.investing.com/rss/news_14.rss', // Economic/regulatory news
];

export const DEFAULT_NEWS_FEEDS = [
  'https://www.investing.com/rss/news_14.rss', // Economic
  'https://www.investing.com/rss/news_25.rss', // Stock market
  'https://www.investing.com/rss/news_1.rss', // Forex
];

// ---------------------------------------------------------------------------
// Simple Hash for Dedup
// ---------------------------------------------------------------------------

export function simpleHash(text: string): string {
  let hash = 0;
  for (let i = 0; i < text.length; i++) {
    const char = text.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash; // 32bit int
  }
  return Math.abs(hash).toString(36);
}

// ---------------------------------------------------------------------------
// Article Creation Helpers
// ---------------------------------------------------------------------------

/** Fetch all active article categories from KV and return their names */
export async function getAvailableCategoryNames(): Promise<{
  names: string[];
  categories: Array<{ id: string; name: string }>;
}> {
  const cats = (await kv.getByPrefix('article_category:')) as Array<{
    id: string;
    name: string;
    is_active?: boolean;
  }>;
  const active = cats.filter((c) => c.is_active !== false);
  return {
    names: active.map((c) => c.name),
    categories: active.map((c) => ({ id: c.id, name: c.name })),
  };
}

/** Resolve a category name (from AI suggestion) to a category ID. Case-insensitive fuzzy match. */
function resolveCategoryId(
  suggestedName: string,
  categories: Array<{ id: string; name: string }>,
): string {
  if (!suggestedName) return '';
  // Exact match first
  const exact = categories.find((c) => c.name.toLowerCase() === suggestedName.toLowerCase());
  if (exact) return exact.id;
  // Partial / includes match
  const partial = categories.find(
    (c) =>
      c.name.toLowerCase().includes(suggestedName.toLowerCase()) ||
      suggestedName.toLowerCase().includes(c.name.toLowerCase()),
  );
  if (partial) {
    log.info('Category fuzzy-matched', { suggested: suggestedName, matched: partial.name });
    return partial.id;
  }
  log.info('No matching category found for AI suggestion', { suggestedName });
  return '';
}

/**
 * Normalise a topic string for cross-pipeline dedup.
 * Strips common prefixes, lowercases, and removes non-alpha characters.
 */
function normaliseTopicForDedup(topic: string): string {
  return topic
    .replace(
      /^(regulatory update|navigate wealth perspective|weekly market commentary|financial news round-up)[:\s—–-]*/i,
      '',
    )
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Check whether a similar topic has already been generated by ANY pipeline
 * within the recent window. Returns true if duplicate.
 */
export async function isTopicDuplicate(
  topic: string,
  currentPipeline: PipelineId,
): Promise<boolean> {
  const normalised = normaliseTopicForDedup(topic);
  if (!normalised || normalised.length < 10) return false; // Too short to be meaningful

  const hash = simpleHash(normalised);
  const existing = (await kv.get(`${GLOBAL_TOPIC_PREFIX}${hash}`)) as {
    pipeline: string;
    articleId: string;
    createdAt: string;
  } | null;

  if (existing && existing.pipeline !== currentPipeline) {
    log.info('Cross-pipeline duplicate detected', {
      topic: normalised.slice(0, 60),
      existingPipeline: existing.pipeline,
      currentPipeline,
    });
    return true;
  }
  return false;
}

/** Record a topic hash after successful article creation (for cross-pipeline dedup) */
export async function recordTopicHash(
  topic: string,
  pipelineId: PipelineId,
  articleId: string,
): Promise<void> {
  const normalised = normaliseTopicForDedup(topic);
  if (!normalised || normalised.length < 10) return;

  const hash = simpleHash(normalised);
  await kv.set(`${GLOBAL_TOPIC_PREFIX}${hash}`, {
    pipeline: pipelineId,
    articleId,
    createdAt: new Date().toISOString(),
  });
}

/** Load recently used Unsplash photo IDs from KV */
export async function getRecentlyUsedImageIds(): Promise<Set<string>> {
  const entries = (await kv.getByPrefix(USED_IMAGE_PREFIX)) as Array<{
    photoId: string;
    usedAt: string;
  }>;
  // Only exclude images used in the last 30 days
  const thirtyDaysAgo = Date.now() - 30 * 24 * 60 * 60 * 1000;
  const recentIds = new Set<string>();
  for (const entry of entries) {
    if (new Date(entry.usedAt).getTime() > thirtyDaysAgo) {
      recentIds.add(entry.photoId);
    }
  }
  return recentIds;
}

/** Record a used Unsplash photo ID for future exclusion */
export async function recordUsedImage(photoId: string): Promise<void> {
  if (!photoId) return;
  await kv.set(`${USED_IMAGE_PREFIX}${photoId}`, {
    photoId,
    usedAt: new Date().toISOString(),
  });
}

export async function createDraftArticle(
  result: GenerateArticleResult,
  categoryId: string,
  typeId: string,
  pipelineId: PipelineId,
): Promise<string> {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();

  // Auto-category: resolve AI-suggested category when none configured
  let resolvedCategoryId = categoryId;
  if (!resolvedCategoryId && result.suggestedCategoryName) {
    const { categories } = await getAvailableCategoryNames();
    resolvedCategoryId = resolveCategoryId(result.suggestedCategoryName, categories);
    if (resolvedCategoryId) {
      log.info('Auto-resolved category for pipeline article', {
        pipeline: pipelineId,
        suggestedName: result.suggestedCategoryName,
        resolvedId: resolvedCategoryId,
      });
    }
  }

  // Check pipeline config for autoPublish setting
  const pipelineConfig = await kv.get(`auto_content:config:${pipelineId}`);
  const shouldAutoPublish = pipelineConfig?.autoPublish === true;

  const article = {
    id,
    title: result.title,
    subtitle: '',
    slug:
      result.suggestedSlug ||
      result.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, ''),
    excerpt: result.excerpt,
    body: result.body,
    category_id: resolvedCategoryId,
    type_id: typeId,
    author_id: '',
    author_name: 'Navigate Wealth',
    hero_image_url: result.suggestedHeroImageUrl || '',
    thumbnail_image_url: result.suggestedThumbnailUrl || '',
    reading_time_minutes: result.readingTimeMinutes,
    status: shouldAutoPublish ? ('published' as const) : ('draft' as const),
    is_featured: false,
    published_at: shouldAutoPublish ? now : null,
    scheduled_for: null,
    seo_title: result.title,
    seo_description: result.suggestedMetaDescription,
    seo_canonical_url: '',
    created_at: now,
    updated_at: now,
    last_edited_by: `auto:${pipelineId}`,
    view_count: 0,
  };

  await kv.set(`article:${id}`, article);

  // Record topic hash for cross-pipeline dedup
  await recordTopicHash(result.title, pipelineId, id);

  log.info(
    shouldAutoPublish ? 'Published article created (auto-publish)' : 'Draft article created',
    {
      id,
      title: result.title,
      pipeline: pipelineId,
      categoryId: resolvedCategoryId,
    },
  );
  return id;
}

/** Resolve the "Insights & Education" type ID from KV */
export async function getDefaultTypeId(): Promise<string> {
  const types = await kv.getByPrefix('article_type:');
  const insightsType = (types as Array<{ id: string; name: string }>).find(
    (t) => t.name === 'Insights & Education',
  );
  return insightsType?.id || '';
}

// ---------------------------------------------------------------------------
// RSS Fetching Helper
// ---------------------------------------------------------------------------

export interface RSSItem {
  title: string;
  link: string;
  pubDate: string;
  description: string;
}

export async function fetchRSSItems(url: string): Promise<RSSItem[]> {
  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        Accept: 'application/rss+xml, application/xml, text/xml, */*',
      },
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      log.error(`RSS fetch failed for ${url}: ${response.status}`);
      return [];
    }

    const xmlText = await response.text();
    const items: RSSItem[] = [];
    const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
    const matches = xmlText.matchAll(itemRegex);

    for (const match of matches) {
      const xml = match[1];
      items.push({
        title: decodeEntities(extractTag(xml, 'title')),
        link: extractTag(xml, 'link'),
        pubDate: extractTag(xml, 'pubDate') || new Date().toISOString(),
        description: decodeEntities(extractTag(xml, 'description')),
      });
    }
    return items.slice(0, 10); // Top 10
  } catch (err) {
    log.error(`RSS fetch error for ${url}`, err);
    return [];
  }
}

export function extractTag(xml: string, tagName: string): string {
  const cdataRegex = new RegExp(
    `<${tagName}[^>]*><!\\[CDATA\\[([\\s\\S]*?)\\]\\]><\\/${tagName}>`,
    'i',
  );
  const cdataMatch = xml.match(cdataRegex);
  if (cdataMatch) return cdataMatch[1].trim();

  const simpleRegex = new RegExp(`<${tagName}[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'i');
  const match = xml.match(simpleRegex);
  return match ? match[1].trim() : '';
}

export function decodeEntities(text: string): string {
  if (!text) return '';
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, ' ');
}

// ---------------------------------------------------------------------------
// Content Source Helpers — rate limiting and source resolution
// ---------------------------------------------------------------------------

/** Get today's date string for daily counter reset (YYYY-MM-DD) */
function todayStr(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Get this week's Monday date string for weekly counter reset */
function weekStartStr(): string {
  const now = new Date();
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -6 : 1); // Monday
  const monday = new Date(now.setDate(diff));
  return monday.toISOString().slice(0, 10);
}

/**
 * Check whether a source has capacity to generate more articles,
 * respecting checkIntervalHours, maxArticlesPerDay, maxArticlesPerWeek.
 * Also resets daily/weekly counters when the date rolls over.
 */
async function checkSourceCapacity(
  src: ContentSource,
): Promise<{ allowed: boolean; reason?: string; source: ContentSource }> {
  const now = new Date();
  let mutated = false;

  // Reset daily counter if the date rolled
  const today = todayStr();
  if (src.dailyResetDate !== today) {
    src.articlesGeneratedToday = 0;
    src.dailyResetDate = today;
    mutated = true;
  }

  // Reset weekly counter if the week rolled
  const weekStart = weekStartStr();
  if (src.weeklyResetDate !== weekStart) {
    src.articlesGeneratedThisWeek = 0;
    src.weeklyResetDate = weekStart;
    mutated = true;
  }

  if (mutated) {
    await kv.set(sourceKey(src.id), src);
  }

  // Check interval
  if (src.checkIntervalHours > 0 && src.lastCheckedAt) {
    const lastChecked = new Date(src.lastCheckedAt);
    const hoursSince = (now.getTime() - lastChecked.getTime()) / (1000 * 60 * 60);
    if (hoursSince < src.checkIntervalHours) {
      return {
        allowed: false,
        reason: `Checked ${Math.round(hoursSince)}h ago (interval: ${src.checkIntervalHours}h)`,
        source: src,
      };
    }
  }

  // Check daily cap
  if (src.maxArticlesPerDay > 0 && src.articlesGeneratedToday >= src.maxArticlesPerDay) {
    return {
      allowed: false,
      reason: `Daily cap reached (${src.articlesGeneratedToday}/${src.maxArticlesPerDay})`,
      source: src,
    };
  }

  // Check weekly cap
  if (src.maxArticlesPerWeek > 0 && src.articlesGeneratedThisWeek >= src.maxArticlesPerWeek) {
    return {
      allowed: false,
      reason: `Weekly cap reached (${src.articlesGeneratedThisWeek}/${src.maxArticlesPerWeek})`,
      source: src,
    };
  }

  return { allowed: true, source: src };
}

/** Increment source counters after successful article generation */
export async function incrementSourceCounters(src: ContentSource, count: number): Promise<void> {
  src.articlesGeneratedToday += count;
  src.articlesGeneratedThisWeek += count;
  src.totalGenerated += count;
  src.lastCheckedAt = new Date().toISOString();
  src.updated_at = new Date().toISOString();
  await kv.set(sourceKey(src.id), src);
}

/** Mark a source as checked (even if no articles were generated) */
export async function markSourceChecked(src: ContentSource): Promise<void> {
  src.lastCheckedAt = new Date().toISOString();
  src.updated_at = new Date().toISOString();
  await kv.set(sourceKey(src.id), src);
}

/** Resolve active sources for a pipeline, falling back to hardcoded defaults */
export async function getSourcesForPipeline(
  pipelineId: PipelineId,
): Promise<{ urls: string[]; sources: ContentSource[]; filterKeywords: string[] }> {
  const allSources = (await kv.getByPrefix(SOURCE_PREFIX)) as ContentSource[];
  const pipelineSources = allSources.filter((s) => s.isActive && s.pipelines.includes(pipelineId));

  if (pipelineSources.length === 0) {
    // Fall back to hardcoded defaults
    const fallbackMap: Record<PipelineId, string[]> = {
      market_commentary: MARKET_RSS_FEEDS,
      regulatory_monitor: REGULATORY_RSS_FEEDS,
      news_commentary: DEFAULT_NEWS_FEEDS,
      calendar_content: [],
    };
    return { urls: fallbackMap[pipelineId] || [], sources: [], filterKeywords: [] };
  }

  // Check capacity for each source, collect eligible URLs
  const urls: string[] = [];
  const eligible: ContentSource[] = [];
  const allKeywords: string[] = [];

  for (const src of pipelineSources) {
    const { allowed, reason, source } = await checkSourceCapacity(src);
    if (allowed) {
      urls.push(source.url);
      eligible.push(source);
      if (source.filterKeywords?.length) {
        allKeywords.push(...source.filterKeywords);
      }
    } else {
      log.info(`Source "${src.name}" skipped: ${reason}`);
    }
  }

  return { urls, sources: eligible, filterKeywords: allKeywords };
}

// ---------------------------------------------------------------------------
// Feed Discovery Helpers
// ---------------------------------------------------------------------------

export function extractFeedTitleFromXml(xml: string): string {
  const channelMatch = xml.match(
    /<channel[\s>][\s\S]*?<title[^>]*>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i,
  );
  if (channelMatch) return decodeHtmlEntitiesSimple(channelMatch[1].trim());

  const feedMatch = xml.match(
    /<feed[\s>][\s\S]*?<title[^>]*>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i,
  );
  if (feedMatch) return decodeHtmlEntitiesSimple(feedMatch[1].trim());

  return '';
}

export function decodeHtmlEntitiesSimple(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}
