/* Originally generated by Figma Make, and since extended by hand:
   listByPrefix, mget, mdel and getByPrefixWhereFieldEquals are ours.
   Treat the stock helpers as the generated part and keep additions below. */

/* Table schema:
CREATE TABLE kv_store_91ed8379 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vpjmdsltwrnpefzcgdmz/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from 'jsr:@supabase/supabase-js@2.49.8';

const client = () =>
  createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);

const prefixUpperBound = (prefix: string): string => `${prefix}\uffff`;

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from('kv_store_91ed8379').upsert({
    key,
    value,
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase
    .from('kv_store_91ed8379')
    .select('value')
    .eq('key', key)
    .maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from('kv_store_91ed8379').delete().eq('key', key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from('kv_store_91ed8379')
    .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from('kv_store_91ed8379')
    .select('key, value')
    .in('key', keys);
  if (error) {
    throw new Error(error.message);
  }
  const valuesByKey = new Map((data ?? []).map((row) => [row.key, row.value]));
  return keys.map((key) => valuesByKey.get(key));
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from('kv_store_91ed8379').delete().in('key', keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from('kv_store_91ed8379')
    .select('key, value')
    .gte('key', prefix)
    .lt('key', prefixUpperBound(prefix))
    .order('key', { ascending: true });
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Search for key-value pairs by prefix, keeping only those whose JSON `value`
// has `field` equal to `equals`.
//
// The filter runs in Postgres, not here. `getByPrefix` returns every row under
// the prefix and leaves the caller to discard most of them, which is fine for a
// one-off admin read and ruinous on a schedule: the every-minute scheduled-
// publish job was pulling all 165 article records (660 kB) out of the database
// once a minute to find the zero that were due (docs/INCIDENTS.md, 2026-09-13).
//
// Pair a hot caller with a partial index on the same predicate, or this is a
// sequential scan that merely moves the waste from the network to the database.
// See migration 20260914083818 for the scheduled-article index.
//
// `field` names a top-level key of the JSON object and is interpolated into the
// PostgREST column expression, so it is restricted to a conservative character
// set rather than trusted.
export const getByPrefixWhereFieldEquals = async (
  prefix: string,
  field: string,
  equals: string,
): Promise<any[]> => {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(field)) {
    throw new Error(`getByPrefixWhereFieldEquals: unsafe field name ${JSON.stringify(field)}`);
  }
  const supabase = client();
  const { data, error } = await supabase
    .from('kv_store_91ed8379')
    .select('key, value')
    .gte('key', prefix)
    .lt('key', prefixUpperBound(prefix))
    .eq(`value->>${field}`, equals)
    .order('key', { ascending: true });
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Lists key/value pairs by prefix with pagination.
export const listByPrefix = async (
  prefix: string,
  options?: { offset?: number; limit?: number; startAfter?: string },
): Promise<Array<{ key: string; value: any }>> => {
  const supabase = client();
  const limit = Math.max(1, options?.limit ?? 100);
  let query = supabase
    .from('kv_store_91ed8379')
    .select('key, value')
    .gte('key', prefix)
    .lt('key', prefixUpperBound(prefix))
    .order('key', { ascending: true });

  if (options?.startAfter) {
    query = query.gt('key', options.startAfter);
  } else {
    const offset = Math.max(0, options?.offset ?? 0);
    query = query.range(offset, offset + limit - 1);
  }

  if (options?.startAfter) {
    query = query.range(0, limit - 1);
  }

  const { data, error } = await query;
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};
