/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_91ed8379 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vpjmdsltwrnpefzcgdmz/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

const prefixUpperBound = (prefix: string): string => `${prefix}\uffff`;

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_91ed8379").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_91ed8379").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_91ed8379").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_91ed8379").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_91ed8379").select("key, value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const valuesByKey = new Map((data ?? []).map((row) => [row.key, row.value]));
  return keys.map((key) => valuesByKey.get(key));
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_91ed8379").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase
    .from("kv_store_91ed8379")
    .select("key, value")
    .gte("key", prefix)
    .lt("key", prefixUpperBound(prefix))
    .order("key", { ascending: true });
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Lists key/value pairs by prefix with pagination.
export const listByPrefix = async (
  prefix: string,
  options?: { offset?: number; limit?: number; startAfter?: string },
): Promise<Array<{ key: string; value: any }>> => {
  const supabase = client()
  const limit = Math.max(1, options?.limit ?? 100);
  let query = supabase
    .from("kv_store_91ed8379")
    .select("key, value")
    .gte("key", prefix)
    .lt("key", prefixUpperBound(prefix))
    .order("key", { ascending: true });

  if (options?.startAfter) {
    query = query.gt("key", options.startAfter);
  } else {
    const offset = Math.max(0, options?.offset ?? 0);
    query = query.range(offset, offset + limit - 1);
  }

  if (options?.startAfter) {
    query = query.range(0, limit - 1);
  }

  const { data, error } = await query;
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};
