/**
 * Auto Provider Group Service
 *
 * Automatically maintains "system" communication groups derived from the
 * product providers (and provider + product-type combinations) that clients
 * actually hold policies with.
 *
 * Examples:
 *   - Any client with a Hollard policy  → "All Hollard Clients"
 *   - A client with an Allan Gray retirement-annuity policy yields BOTH
 *       "All Allan Gray Clients"  AND  "Allan Gray Retirement Planning"
 *
 * These groups are dynamic — they carry a `filterConfig.productFilters` rule —
 * so the existing group-matcher resolves membership and the existing campaign
 * send path targets them like any other dynamic group. They are flagged
 * `autoGenerated: true` and `type: 'system'` so they cannot be edited or
 * deleted by hand, and they are re-synced (created / updated / removed)
 * automatically as client policies change.
 *
 * KV keys:
 *   - communication:groups:{id}                       (the group itself)
 *   - communication:auto_provider_groups:last_sync    (last sync timestamp)
 */

import * as kv from './kv_store.tsx';
import * as repo from './communication-repo.ts';
import { recalculateSingleGroupMembership } from './group-matcher.ts';
import type { MatcherClient } from './group-matcher.ts';
import { createModuleLogger } from './stderr-logger.ts';
import { POLICY_CATEGORY_LABELS } from './integrations-document-storage.ts';
import type { Group } from './communication-types.ts';

const log = createModuleLogger('provider-group');

/** Well-known ID prefix for auto-generated provider groups. */
export const AUTO_PROVIDER_GROUP_PREFIX = 'sys_provider_';

const GROUP_KV_PREFIX = 'communication:groups:';
const LAST_SYNC_KEY = 'communication:auto_provider_groups:last_sync';
const PROVIDER_GROUP_COLOR = '#0f766e';

function titleCase(value: string): string {
  return value
    .replace(/[_-]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
    .split(' ')
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');
}

/**
 * Human-readable product-type label for a raw category id / type string.
 * Uses the shared POLICY_CATEGORY_LABELS map, falling back to a title-cased
 * version of the raw value for unknown / free-text types.
 */
export function categoryLabel(type: string): string {
  const raw = (type || '').trim();
  return POLICY_CATEGORY_LABELS[raw] || POLICY_CATEGORY_LABELS[raw.toLowerCase()] || titleCase(raw);
}

/** URL/ID-safe slug used to build deterministic group IDs. */
function slug(value: string): string {
  return (value || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export interface AutoProviderGroupSpec {
  id: string;
  name: string;
  description: string;
  filterConfig: { productFilters: Array<{ provider?: string; type?: string }> };
  /** Lower-cased provider key (for dedupe / diagnostics). */
  providerKey: string;
  /** Lower-cased product-type key, present only for provider+type groups. */
  typeKey?: string;
}

/**
 * Pure derivation: given the active matcher clients, return the full set of
 * auto provider groups that SHOULD exist — one per distinct provider, plus one
 * per distinct provider+product-type combination. Providers/types are matched
 * case-insensitively; the first-seen spelling is used for display.
 *
 * No KV access — kept pure so it is trivially unit-testable.
 */
export function deriveAutoProviderGroups(clients: MatcherClient[]): AutoProviderGroupSpec[] {
  // providerKey -> display spelling
  const providerDisplay = new Map<string, string>();
  // `${providerKey}__${typeKey}` -> { provider display, type display }
  const comboDisplay = new Map<string, { provider: string; type: string }>();

  for (const client of clients) {
    for (const product of client.products || []) {
      const providerRaw = (product.provider || '').trim();
      if (!providerRaw) continue;

      const providerKey = providerRaw.toLowerCase();
      if (!providerDisplay.has(providerKey)) {
        providerDisplay.set(providerKey, providerRaw);
      }

      const typeRaw = (product.type || '').trim();
      if (typeRaw) {
        const comboKey = `${providerKey}__${typeRaw.toLowerCase()}`;
        if (!comboDisplay.has(comboKey)) {
          comboDisplay.set(comboKey, { provider: providerRaw, type: typeRaw });
        }
      }
    }
  }

  const specs: AutoProviderGroupSpec[] = [];

  // One group per provider — "All <Provider> Clients"
  for (const [providerKey, provider] of providerDisplay) {
    specs.push({
      id: `${AUTO_PROVIDER_GROUP_PREFIX}${slug(provider)}`,
      name: `All ${provider} Clients`,
      description: `Clients with at least one ${provider} product. Automatically maintained.`,
      filterConfig: { productFilters: [{ provider }] },
      providerKey,
    });
  }

  // One group per provider + product-type — e.g. "Allan Gray Retirement Planning"
  for (const [comboKey, { provider, type }] of comboDisplay) {
    const typeKey = comboKey.split('__')[1];
    const label = categoryLabel(type);
    specs.push({
      id: `${AUTO_PROVIDER_GROUP_PREFIX}${slug(provider)}__${slug(type)}`,
      name: `${provider} ${label}`,
      description: `Clients with a ${provider} ${label} product. Automatically maintained.`,
      filterConfig: { productFilters: [{ provider, type }] },
      providerKey: comboKey.split('__')[0],
      typeKey,
    });
  }

  // Stable, alphabetical ordering for predictable display.
  return specs.sort((a, b) => a.name.localeCompare(b.name));
}

/** True when a group ID belongs to an auto-generated provider group. */
export function isAutoProviderGroup(groupId: string): boolean {
  return typeof groupId === 'string' && groupId.startsWith(AUTO_PROVIDER_GROUP_PREFIX);
}

export async function getLastSyncAt(): Promise<string | null> {
  return ((await kv.get(LAST_SYNC_KEY)) as string | null) || null;
}

/** True when auto provider groups have never synced or are older than `intervalMs`. */
export async function isSyncStale(intervalMs: number): Promise<boolean> {
  const last = await getLastSyncAt();
  if (!last) return true;
  return Date.now() - new Date(last).getTime() > intervalMs;
}

export interface ProviderGroupSyncResult {
  created: number;
  updated: number;
  removed: number;
  total: number;
}

/**
 * Reconcile the persisted auto provider groups with what the current client
 * base requires: create missing groups, refresh existing ones (name,
 * description, membership), and delete groups whose provider/type no longer
 * has any clients.
 *
 * Accepts optional pre-fetched matcher clients so callers that already paid
 * for the (expensive) fetch don't pay again.
 */
export async function syncAutoProviderGroups(
  matcherClients?: MatcherClient[],
): Promise<ProviderGroupSyncResult> {
  const clients = matcherClients || (await repo.fetchMatcherClients());
  const specs = deriveAutoProviderGroups(clients);
  const desiredIds = new Set(specs.map((s) => s.id));

  const allGroups = ((await kv.getByPrefix(GROUP_KV_PREFIX)) as Group[]) || [];
  const existingAuto = allGroups.filter(
    (g) => isAutoProviderGroup(g.id) || g.autoGenerated === true,
  );
  const existingById = new Map(existingAuto.map((g) => [g.id, g]));

  const now = new Date().toISOString();
  let created = 0;
  let updated = 0;
  let removed = 0;

  for (const spec of specs) {
    const existing = existingById.get(spec.id);

    const group: Group = existing
      ? { ...existing }
      : {
          id: spec.id,
          name: spec.name,
          description: spec.description,
          color: PROVIDER_GROUP_COLOR,
          type: 'system',
          clientIds: [],
          externalContacts: [],
          filterConfig: spec.filterConfig,
          clientCount: 0,
          createdBy: 'system',
          createdAt: now,
          updatedAt: now,
          autoGenerated: true,
        };

    // Keep metadata current (provider spelling / label changes etc.).
    group.name = spec.name;
    group.description = spec.description;
    group.filterConfig = spec.filterConfig;
    group.type = 'system';
    group.autoGenerated = true;
    group.color = group.color || PROVIDER_GROUP_COLOR;

    // Resolve current membership from the already-fetched client set.
    const recalculated = recalculateSingleGroupMembership(group, clients);
    group.clientIds = (recalculated.clientIds || []) as string[];
    group.clientCount = group.clientIds.length;
    group.updatedAt = now;

    await kv.set(`${GROUP_KV_PREFIX}${spec.id}`, group);
    if (existing) updated++;
    else created++;
  }

  // Retire auto groups whose provider/type combination no longer exists.
  for (const group of existingAuto) {
    if (!desiredIds.has(group.id)) {
      await kv.del(`${GROUP_KV_PREFIX}${group.id}`);
      removed++;
    }
  }

  await kv.set(LAST_SYNC_KEY, now);

  log.info('Auto provider groups synced', {
    created,
    updated,
    removed,
    total: specs.length,
  });

  return { created, updated, removed, total: specs.length };
}
