/**
 * Auto Provider Group Service
 *
 * Automatically maintains "system" communication groups derived from the
 * product providers (and provider + product-type combinations) that clients
 * actually hold policies with.
 *
 * Examples:
 *   - Any client with a Hollard policy  → "All Hollard Clients"
 *   - A client with an Allan Gray retirement-annuity policy yields BOTH
 *       "All Allan Gray Clients"  AND  "Allan Gray Retirement Planning"
 *
 * These groups are dynamic — they carry a `filterConfig.productFilters` rule —
 * so the existing group-matcher resolves membership and the existing campaign
 * send path targets them like any other dynamic group. They are flagged
 * `autoGenerated: true` and `type: 'system'` so they cannot be edited or
 * deleted by hand, and they are re-synced (created / updated / removed)
 * automatically as client policies change.
 *
 * KV keys:
 *   - communication:groups:{id}                       (the group itself)
 *   - communication:auto_provider_groups:last_sync    (last sync timestamp)
 */

import * as kv from './kv_store.tsx';
import * as repo from './communication-repo.ts';
import { recalculateSingleGroupMembership } from './group-matcher.ts';
import type { MatcherClient } from './group-matcher.ts';
import { createModuleLogger } from './stderr-logger.ts';
import { POLICY_CATEGORY_LABELS } from './integrations-document-storage.ts';
import type { Group } from './communication-types.ts';
import {
  communicationGroups,
  LAST_PROVIDER_SYNC_KEY,
} from './repositories/communication-groups-repository.ts';

const log = createModuleLogger('provider-group');

/** Well-known ID prefix for auto-generated provider groups. */
export const AUTO_PROVIDER_GROUP_PREFIX = 'sys_provider_';

const PROVIDER_GROUP_COLOR = '#0f766e';

function titleCase(value: string): string {
  return value
    .replace(/[_-]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
    .split(' ')
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');
}

/**
 * Human-readable product-type label for a raw category id / type string.
 * Uses the shared POLICY_CATEGORY_LABELS map, falling back to a title-cased
 * version of the raw value for unknown / free-text types.
 */
export function categoryLabel(type: string): string {
  const raw = (type || '').trim();
  return POLICY_CATEGORY_LABELS[raw] || POLICY_CATEGORY_LABELS[raw.toLowerCase()] || titleCase(raw);
}

/** URL/ID-safe slug used to build deterministic group IDs. */
function slug(value: string): string {
  return (value || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export interface AutoProviderGroupSpec {
  id: string;
  name: string;
  description: string;
  filterConfig: { productFilters: Array<{ provider?: string; type?: string }> };
  /** Slug-based provider key — the basis of the group ID. */
  providerKey: string;
  /** Slug-based product-type key, present only for provider+type groups. */
  typeKey?: string;
}

/**
 * Pure derivation: given the active matcher clients, return the full set of
 * auto provider groups that SHOULD exist — one per distinct provider, plus one
 * per distinct provider+product-type combination.
 *
 * Grouping identity is slug-based (so "Risk Planning" and "risk_planning"
 * resolve to the same group). Because the group-matcher compares the raw
 * lowercased strings — which a slug does NOT preserve (underscores vs spaces) —
 * each group's filterConfig keeps ONE productFilter rule per distinct raw
 * representation seen. The matcher ORs the rules, so every client is captured
 * regardless of which spelling their policy used.
 *
 * No KV access — kept pure so it is trivially unit-testable.
 */
export function deriveAutoProviderGroups(clients: MatcherClient[]): AutoProviderGroupSpec[] {
  interface ProviderAcc {
    display: string;
    rawProviders: Map<string, string>; // rawProvider -> rawProvider (dedup set)
  }
  interface ComboAcc {
    providerDisplay: string;
    typeDisplay: string;
    rules: Map<string, { provider: string; type: string }>; // ruleKey -> raw rule
  }

  const providers = new Map<string, ProviderAcc>(); // providerKey -> acc
  const combos = new Map<string, ComboAcc>(); // `${providerKey}__${typeKey}` -> acc

  for (const client of clients) {
    for (const product of client.products || []) {
      const providerRaw = (product.provider || '').trim();
      if (!providerRaw) continue;

      const providerKey = slug(providerRaw);
      if (!providerKey) continue;

      let pAcc = providers.get(providerKey);
      if (!pAcc) {
        pAcc = { display: providerRaw, rawProviders: new Map() };
        providers.set(providerKey, pAcc);
      }
      // Dedup raw spellings case-insensitively — the matcher already compares
      // lowercased, so only spellings that differ beyond case need their own rule.
      if (!pAcc.rawProviders.has(providerRaw.toLowerCase())) {
        pAcc.rawProviders.set(providerRaw.toLowerCase(), providerRaw);
      }

      const typeRaw = (product.type || '').trim();
      if (typeRaw) {
        const typeKey = slug(typeRaw);
        if (!typeKey) continue;

        const comboKey = `${providerKey}__${typeKey}`;
        let cAcc = combos.get(comboKey);
        if (!cAcc) {
          cAcc = { providerDisplay: providerRaw, typeDisplay: typeRaw, rules: new Map() };
          combos.set(comboKey, cAcc);
        }
        const ruleKey = `${providerRaw.toLowerCase()}||${typeRaw.toLowerCase()}`;
        if (!cAcc.rules.has(ruleKey)) {
          cAcc.rules.set(ruleKey, { provider: providerRaw, type: typeRaw });
        }
      }
    }
  }

  const specs: AutoProviderGroupSpec[] = [];

  // One group per provider — "All <Provider> Clients"
  for (const [providerKey, acc] of providers) {
    specs.push({
      id: `${AUTO_PROVIDER_GROUP_PREFIX}${providerKey}`,
      name: `All ${acc.display} Clients`,
      description: `Clients with at least one ${acc.display} product. Automatically maintained.`,
      filterConfig: {
        productFilters: [...acc.rawProviders.values()].map((provider) => ({ provider })),
      },
      providerKey,
    });
  }

  // One group per provider + product-type — e.g. "Allan Gray Retirement Planning"
  for (const [comboKey, acc] of combos) {
    const [providerKey, typeKey] = comboKey.split('__');
    const label = categoryLabel(acc.typeDisplay);
    specs.push({
      id: `${AUTO_PROVIDER_GROUP_PREFIX}${comboKey}`,
      name: `${acc.providerDisplay} ${label}`,
      description: `Clients with a ${acc.providerDisplay} ${label} product. Automatically maintained.`,
      filterConfig: { productFilters: [...acc.rules.values()] },
      providerKey,
      typeKey,
    });
  }

  // Stable, alphabetical ordering for predictable display.
  return specs.sort((a, b) => a.name.localeCompare(b.name));
}

/** True when a group ID belongs to an auto-generated provider group. */
export function isAutoProviderGroup(groupId: string): boolean {
  return typeof groupId === 'string' && groupId.startsWith(AUTO_PROVIDER_GROUP_PREFIX);
}

export async function getLastSyncAt(): Promise<string | null> {
  return ((await kv.get(LAST_PROVIDER_SYNC_KEY)) as string | null) || null;
}

/** True when auto provider groups have never synced or are older than `intervalMs`. */
export async function isSyncStale(intervalMs: number): Promise<boolean> {
  const last = await getLastSyncAt();
  if (!last) return true;
  return Date.now() - new Date(last).getTime() > intervalMs;
}

export interface ProviderGroupSyncResult {
  created: number;
  updated: number;
  removed: number;
  total: number;
}

/**
 * Reconcile the persisted auto provider groups with what the current client
 * base requires: create missing groups, refresh existing ones (name,
 * description, membership), and delete groups whose provider/type no longer
 * has any clients.
 *
 * Accepts optional pre-fetched matcher clients so callers that already paid
 * for the (expensive) fetch don't pay again.
 */
export async function syncAutoProviderGroups(
  matcherClients?: MatcherClient[],
): Promise<ProviderGroupSyncResult> {
  const clients = matcherClients || (await repo.fetchMatcherClients());
  const specs = deriveAutoProviderGroups(clients);
  const desiredIds = new Set(specs.map((s) => s.id));

  // Deliberately unbounded: the sync must reconcile against EVERY existing
  // auto group to know which ones to retire, so a page would produce wrong
  // deletions. Stated through listAll's required reason rather than hidden in
  // a bare getByPrefix — see repositories/kv-repository.ts.
  const allGroups = await communicationGroups.listAll(
    'provider-group sync reconciles the full group set to retire stale auto groups',
  );
  const existingAuto = allGroups.filter(
    (g) => isAutoProviderGroup(g.id) || g.autoGenerated === true,
  );
  const existingById = new Map(existingAuto.map((g) => [g.id, g]));

  const now = new Date().toISOString();
  let created = 0;
  let updated = 0;
  let removed = 0;

  for (const spec of specs) {
    const existing = existingById.get(spec.id);

    const group: Group = existing
      ? { ...existing }
      : {
          id: spec.id,
          name: spec.name,
          description: spec.description,
          color: PROVIDER_GROUP_COLOR,
          type: 'system',
          clientIds: [],
          externalContacts: [],
          filterConfig: spec.filterConfig,
          clientCount: 0,
          createdBy: 'system',
          createdAt: now,
          updatedAt: now,
          autoGenerated: true,
        };

    // Keep metadata current (provider spelling / label changes etc.).
    group.name = spec.name;
    group.description = spec.description;
    group.filterConfig = spec.filterConfig;
    group.type = 'system';
    group.autoGenerated = true;
    group.color = group.color || PROVIDER_GROUP_COLOR;

    // Resolve current membership from the already-fetched client set.
    const recalculated = recalculateSingleGroupMembership(group, clients);
    group.clientIds = (recalculated.clientIds || []) as string[];
    group.clientCount = group.clientIds.length;
    group.updatedAt = now;

    await communicationGroups.put(spec.id, group);
    if (existing) updated++;
    else created++;
  }

  // Retire auto groups whose provider/type combination no longer exists.
  for (const group of existingAuto) {
    if (!desiredIds.has(group.id)) {
      await communicationGroups.remove(group.id);
      removed++;
    }
  }

  await kv.set(LAST_PROVIDER_SYNC_KEY, now);

  log.info('Auto provider groups synced', {
    created,
    updated,
    removed,
    total: specs.length,
  });

  return { created, updated, removed, total: specs.length };
}
