export type ProductCategoryId = 
  | 'risk_planning' 
  | 'medical_aid' 
  | 'retirement_planning' 
  | 'retirement_pre'
  | 'retirement_post'
  | 'investments'
  | 'investments_voluntary'
  | 'investments_guaranteed'
  | 'employee_benefits' 
  | 'employee_benefits_risk'
  | 'employee_benefits_retirement'
  | 'tax_planning' 
  | 'estate_planning';

export const PRODUCT_CATEGORIES = [
  { id: 'risk_planning', name: 'Risk Planning' },
  { id: 'medical_aid', name: 'Medical Aid' },
  { id: 'retirement_planning', name: 'Retirement Planning' },
  { id: 'retirement_pre', name: 'Pre-Retirement' },
  { id: 'retirement_post', name: 'Post-Retirement' },
  { id: 'investments', name: 'Investments' },
  { id: 'investments_voluntary', name: 'Voluntary Investments' },
  { id: 'investments_guaranteed', name: 'Guaranteed Investments' },
  { id: 'employee_benefits', name: 'Employee Benefits' },
  { id: 'employee_benefits_risk', name: 'Risk' },
  { id: 'employee_benefits_retirement', name: 'Retirement' },
  { id: 'tax_planning', name: 'Tax Planning' },
  { id: 'estate_planning', name: 'Estate Planning' },
] as const;

export const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'number', label: 'Number' },
  { value: 'currency', label: 'Currency' },
  { value: 'percentage', label: 'Percentage (%)' },
  { value: 'date', label: 'Date' },
  { value: 'boolean', label: 'Yes/No' },
  { value: 'dropdown', label: 'Dropdown' },
  { value: 'long_text', label: 'Long Text' },
] as const;

export interface ProductField {
  id: string;
  name: string;
  type: typeof FIELD_TYPES[number]['value'] | string; // Allowing string for flexibility
  required: boolean;
  options?: string[]; // For dropdowns
  system?: boolean; // For internal fields
  keyId?: string; // Optional mapping to a ProductKey
}

export interface CategoryTableStructure {
  categoryId: string;
  fields: ProductField[];
}

export interface BrokerConsultant {
  id: string;
  name: string;
  email: string;
  phone: string;
  providerId: string;
  specialization: string[];
  active: boolean;
}

// ----------------------------------------------------------------------------
// DATA TRANSFER OBJECTS (DTOs)
// Directly mirroring Backend types from /supabase/functions/server/product-management-types.ts
// ----------------------------------------------------------------------------

export type ProviderType = 
  | 'insurance'
  | 'investment'
  | 'medical_aid'
  | 'retirement'
  | 'other';

export interface ProviderDTO {
  id: string;
  name: string;
  code: string;
  type: ProviderType;
  description?: string;
  category_ids?: string[];
  logo_url?: string;
  website?: string;
  contact_email?: string;
  contact_phone?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// ----------------------------------------------------------------------------
// DOMAIN MODELS (Frontend)
// ----------------------------------------------------------------------------

export interface ProductProvider {
  id: string;
  name: string;
  code?: string; // Optional for backward compatibility during migration
  type?: ProviderType;
  description?: string;
  logo?: string; // Mapped from logo_url
  website?: string;
  contactEmail?: string; // Mapped from contact_email
  contactPhone?: string; // Mapped from contact_phone
  
  // UI-specific / Enriched fields
  brokerConsultants: BrokerConsultant[];
  supportedProducts: string[];
  
  active: boolean; // Mapped from is_active
  categoryIds: string[]; // Mapped from category_ids
  
  createdAt?: string;
  updatedAt?: string;
}

// Alias for compatibility
export type Provider = ProductProvider;

export interface SaveProviderRequest {
  name: string;
  active: boolean;
  logo?: string;
  categoryIds: string[];
  description?: string;
  website?: string;
  contactEmail?: string;
  contactPhone?: string;
  // Code is auto-generated by backend usually, but can be passed if needed
}

export interface SaveSchemaRequest {
  categoryId: string;
  fields: ProductField[];
}

// Integrations (Legacy/Hybrid)
export interface IntegrationProvider {
  id: string;
  name: string;
  description?: string;
  categoryIds: string[];
  logoUrl?: string;
  lastAttempted?: string;
  lastUpdateStatus?: 'success' | 'failed' | 'never';
  lastSuccessful?: string;
}

export interface IntegrationStats {
  lastAttempted: string;
  lastUpdateStatus: 'success' | 'failed' | null;
  lastSuccessful: string;
}

export interface IntegrationConfig {
  providerId: string;
  categoryId: string;
  updatedAt: string;
  updatedBy: string;
  fieldMapping: Record<string, string>;
  settings: {
    autoMap: boolean;
    ignoreUnmatched: boolean;
    strictMode: boolean;
  };
}

export interface UploadPreviewResponse {
  success: boolean;
  preview?: {
    totalRows: number;
    mappedColumns: string[];
    unmappedColumns: string[];
    validationErrors: string[];
    sampleData: Record<string, unknown>[];
  };
  result?: {
    insertedRows: number;
    historyId: string;
  };
  error?: string;
}

// ----------------------------------------------------------------------------
// KEY MANAGER TYPES
// ----------------------------------------------------------------------------

export type ProductKeyCategory = 
  | 'risk'
  | 'medical_aid'
  | 'retirement_pre'
  | 'retirement_post'
  | 'invest_voluntary'
  | 'invest_guaranteed'
  | 'employee_benefits'
  | 'employee_benefits_risk'
  | 'employee_benefits_retirement'
  | 'estate_planning'
  | 'tax'
  | 'profile_personal'
  | 'profile_contact'
  | 'profile_identity'
  | 'profile_address'
  | 'profile_employment'
  | 'profile_health'
  | 'profile_family'
  | 'profile_banking'
  | 'profile_risk'
  | 'profile_financial';

export interface ProductKey {
  id: string;
  category: ProductKeyCategory;
  name: string;
  description: string;
  dataType: 'number' | 'currency' | 'percentage' | 'date' | 'text' | 'boolean';
  isCalculated?: boolean; // True for totals/calculated fields, false/undefined for assignable fields
  calculatedFrom?: string[]; // Array of key IDs that this total is calculated from
  isRecommendation?: boolean; // True for keys that store FNA recommended values
}

export interface FieldKeyMapping {
  fieldId: string;
  keyId: string;
  categoryId: string; // The product category (risk_planning, etc.)
}