export type ProductCategoryId = 
  | 'risk_planning' 
  | 'medical_aid' 
  | 'retirement_planning' 
  | 'retirement_pre'
  | 'retirement_post'
  | 'investments'
  | 'investments_voluntary'
  | 'investments_guaranteed'
  | 'employee_benefits' 
  | 'employee_benefits_risk'
  | 'employee_benefits_retirement'
  | 'tax_planning' 
  | 'estate_planning';

export const PRODUCT_CATEGORIES = [
  { id: 'risk_planning', name: 'Risk Planning' },
  { id: 'medical_aid', name: 'Medical Aid' },
  { id: 'retirement_planning', name: 'Retirement Planning' },
  { id: 'retirement_pre', name: 'Pre-Retirement' },
  { id: 'retirement_post', name: 'Post-Retirement' },
  { id: 'investments', name: 'Investments' },
  { id: 'investments_voluntary', name: 'Voluntary Investments' },
  { id: 'investments_guaranteed', name: 'Guaranteed Investments' },
  { id: 'employee_benefits', name: 'Employee Benefits' },
  { id: 'employee_benefits_risk', name: 'Risk' },
  { id: 'employee_benefits_retirement', name: 'Retirement' },
  { id: 'tax_planning', name: 'Tax Planning' },
  { id: 'estate_planning', name: 'Estate Planning' },
] as const;

export const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'number', label: 'Number' },
  { value: 'currency', label: 'Currency' },
  { value: 'percentage', label: 'Percentage (%)' },
  { value: 'date', label: 'Date' },
  { value: 'boolean', label: 'Yes/No' },
  { value: 'dropdown', label: 'Dropdown' },
  { value: 'long_text', label: 'Long Text' },
] as const;

export interface ProductField {
  id: string;
  name: string;
  type: typeof FIELD_TYPES[number]['value'] | string; // Allowing string for flexibility
  required: boolean;
  options?: string[]; // For dropdowns
  system?: boolean; // For internal fields
  keyId?: string; // Optional mapping to a ProductKey
}

export interface CategoryTableStructure {
  categoryId: string;
  fields: ProductField[];
}

export interface BrokerConsultant {
  id: string;
  name: string;
  email: string;
  phone: string;
  providerId: string;
  specialization: string[];
  active: boolean;
}

// ----------------------------------------------------------------------------
// DATA TRANSFER OBJECTS (DTOs)
// Directly mirroring Backend types from /supabase/functions/server/product-management-types.ts
// ----------------------------------------------------------------------------

export type ProviderType = 
  | 'insurance'
  | 'investment'
  | 'medical_aid'
  | 'retirement'
  | 'other';

export interface ProviderDTO {
  id: string;
  name: string;
  code: string;
  type: ProviderType;
  description?: string;
  category_ids?: string[];
  logo_url?: string;
  website?: string;
  contact_email?: string;
  contact_phone?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// ----------------------------------------------------------------------------
// DOMAIN MODELS (Frontend)
// ----------------------------------------------------------------------------

export interface ProductProvider {
  id: string;
  name: string;
  code?: string; // Optional for backward compatibility during migration
  type?: ProviderType;
  description?: string;
  logo?: string; // Mapped from logo_url
  website?: string;
  contactEmail?: string; // Mapped from contact_email
  contactPhone?: string; // Mapped from contact_phone
  
  // UI-specific / Enriched fields
  brokerConsultants: BrokerConsultant[];
  supportedProducts: string[];
  
  active: boolean; // Mapped from is_active
  categoryIds: string[]; // Mapped from category_ids
  
  createdAt?: string;
  updatedAt?: string;
}

// Alias for compatibility
export type Provider = ProductProvider;

export interface SaveProviderRequest {
  name: string;
  active: boolean;
  logo?: string;
  categoryIds: string[];
  description?: string;
  website?: string;
  contactEmail?: string;
  contactPhone?: string;
  // Code is auto-generated by backend usually, but can be passed if needed
}

export interface SaveSchemaRequest {
  categoryId: string;
  fields: ProductField[];
}

// Integrations (Legacy/Hybrid)
export interface IntegrationProvider {
  id: string;
  name: string;
  description?: string;
  categoryIds: string[];
  logoUrl?: string;
  lastAttempted?: string;
  lastUpdateStatus?: 'success' | 'failed' | 'never';
  lastSuccessful?: string;
}

export interface IntegrationStats {
  lastAttempted: string;
  lastUpdateStatus: 'success' | 'failed' | null;
  lastSuccessful: string;
}

export interface IntegrationConfig {
  providerId?: string;
  categoryId?: string;
  updatedAt?: string;
  updatedBy?: string;
  fieldMapping: Record<string, string>;
  settings: IntegrationMappingConfig;
}

export interface IntegrationMappingConfig {
  autoMap: boolean;
  ignoreUnmatched: boolean;
  strictMode: boolean;
  autoPublish?: boolean;
}

export interface PreviewData {
  headers: string[];
  rows: Record<string, unknown>[];
  validationErrors?: string[];
}

export interface IntegrationSyncDiff {
  fieldId: string;
  fieldName: string;
  oldValue: unknown;
  newValue: unknown;
}

export interface IntegrationSyncRow {
  id: string;
  rowNumber: number;
  rawData: Record<string, unknown>;
  mappedData: Record<string, unknown>;
  policyNumber: string;
  normalizedPolicyNumber: string;
  matchStatus: 'matched' | 'unmatched' | 'duplicate' | 'invalid';
  publishStatus: 'pending' | 'auto_eligible' | 'held' | 'published' | 'skipped' | 'failed';
  autoPublishEligible: boolean;
  validationErrors: string[];
  warnings: string[];
  diffs: IntegrationSyncDiff[];
  clientId?: string;
  policyId?: string;
  providerName?: string;
}

export interface IntegrationSyncRun {
  id: string;
  providerId: string;
  providerName: string;
  categoryId: string;
  fileName: string;
  source: 'spreadsheet' | 'portal';
  status: 'staged' | 'published' | 'partially_published' | 'failed';
  createdAt: string;
  updatedAt: string;
  mappingVersion: string;
  autoPublish: boolean;
  summary: {
    totalRows: number;
    matchedRows: number;
    unmatchedRows: number;
    duplicateRows: number;
    invalidRows: number;
    changedRows: number;
    noChangeRows: number;
    autoEligibleRows: number;
    publishedRows: number;
    heldRows: number;
  };
  rows: IntegrationSyncRow[];
}

export type PortalJobStatus = 'queued' | 'running' | 'waiting_for_otp' | 'discovering' | 'discovery_ready' | 'extracting' | 'dry_run_ready' | 'staging' | 'staged' | 'failed' | 'cancelled';
export type PortalJobRunMode = 'discover' | 'dry-run' | 'run';
export type PortalAutomationHost = 'github_actions' | 'hosted_worker' | 'manual';
export type PortalJobItemStatus = 'queued' | 'in_progress' | 'completed' | 'failed' | 'skipped';

export interface PortalCredentialProfile {
  id: string;
  label: string;
  source: 'environment' | 'supabase_kv' | 'supabase_vault';
  usernameEnvVar?: string;
  passwordEnvVar?: string;
  usernameSecretName?: string;
  passwordSecretName?: string;
}

export interface PortalCredentialStatus {
  providerId: string;
  profileId: string;
  hasUsername: boolean;
  hasPassword: boolean;
  updatedAt?: string;
  updatedBy?: string;
}

export interface PortalFlowField {
  sourceHeader: string;
  selector: string;
  labels?: string[];
  attribute?: 'text' | 'value' | 'href' | string;
  required?: boolean;
  transform?: 'trim' | 'number' | 'date' | string;
}

export interface PortalFlowStep {
  id: string;
  action: 'goto' | 'click' | 'fill' | 'wait_for_selector' | 'wait_for_url' | 'press';
  selector?: string;
  url?: string;
  value?: string;
  key?: string;
  timeoutMs?: number;
  description?: string;
}

export interface PortalProviderFlow {
  id: string;
  providerId: string;
  name: string;
  loginUrl: string;
  credentialProfiles: PortalCredentialProfile[];
  login: {
    usernameSelector: string;
    passwordSelector: string;
    submitSelector: string;
  };
  otp: {
    mode: 'manual_sms';
    detectionSelectors: string[];
    inputSelector: string;
    submitSelector: string;
    timeoutMs: number;
    instructions: string;
  };
  navigation: {
    postLoginUrl?: string;
    policyListSteps?: PortalFlowStep[];
    clientListSelector?: string;
    clientRowSelector?: string;
    nextPageSelector?: string;
  };
  search?: {
    mode: 'policy_number';
    searchPageUrl?: string;
    searchInputSelector?: string;
    searchInputLabels?: string[];
    submitSelector?: string;
    resultContainerSelector?: string;
    resultLinkSelector?: string;
    resultPolicyNumberSelector?: string;
    noResultsText?: string[];
    instructions?: string;
  };
  extraction: {
    policyRowSelector?: string;
    fields: PortalFlowField[];
  };
  notes: string[];
  needsDiscovery?: boolean;
  updatedAt: string;
}

export interface PortalSyncJob {
  id: string;
  providerId: string;
  providerName: string;
  categoryId: string;
  status: PortalJobStatus;
  runMode?: PortalJobRunMode;
  automationHost?: PortalAutomationHost;
  flowId: string;
  credentialProfileId: string;
  workerId?: string;
  actionsRunId?: number;
  actionsRunUrl?: string;
  actionsDispatchError?: string;
  createdAt: string;
  updatedAt: string;
  startedAt?: string;
  completedAt?: string;
  currentStep?: string;
  message?: string;
  extractedRows?: number;
  stagedRunId?: string;
  discoveryReportId?: string;
  error?: string;
  currentItemId?: string;
  currentClientName?: string;
  currentPolicyNumber?: string;
  queueSummary?: PortalJobQueueSummary;
}

export interface PortalJobQueueSummary {
  total: number;
  queued: number;
  inProgress: number;
  completed: number;
  failed: number;
  skipped: number;
}

export interface PortalJobPolicyItem {
  id: string;
  jobId: string;
  providerId: string;
  providerName: string;
  categoryId: string;
  clientId: string;
  clientName: string;
  policyId: string;
  policyNumber: string;
  normalizedPolicyNumber: string;
  status: PortalJobItemStatus;
  currentStep?: string;
  message?: string;
  error?: string;
  workerId?: string;
  rawData?: Record<string, unknown>;
  extractedData?: Record<string, unknown>;
  matchConfidence?: 'high' | 'medium' | 'low';
  createdAt: string;
  updatedAt: string;
  startedAt?: string;
  completedAt?: string;
}

export interface PortalDiscoveryReport {
  id: string;
  jobId: string;
  providerId: string;
  categoryId: string;
  createdAt: string;
  mode: 'discover' | 'dry-run';
  urlHost: string;
  title?: string;
  summary: {
    inputCount: number;
    buttonCount: number;
    linkCount: number;
    tableCount: number;
    candidatePolicyTables: number;
    extractedRowCount?: number;
  };
  selectorCandidates: Array<{
    purpose: 'input' | 'button' | 'link' | 'table' | 'policy_row' | 'field';
    selector: string;
    tag?: string;
    type?: string;
    role?: string;
    label?: string;
    confidence: 'low' | 'medium' | 'high';
    notes?: string;
  }>;
  tableSummaries: Array<{
    selector: string;
    headerTexts: string[];
    rowCount: number;
  }>;
  warnings: string[];
}

export interface UploadPreviewResponse {
  success: boolean;
  preview?: {
    totalRows: number;
    mappedColumns: string[];
    unmappedColumns: string[];
    validationErrors: string[];
    sampleData: Record<string, unknown>[];
  };
  result?: {
    insertedRows: number;
    stagedRows?: number;
    historyId: string;
    runId?: string;
    autoPublished?: boolean;
    stagedRun?: IntegrationSyncRun;
  };
  error?: string;
}

// ----------------------------------------------------------------------------
// KEY MANAGER TYPES
// ----------------------------------------------------------------------------

export type ProductKeyCategory = 
  | 'risk'
  | 'medical_aid'
  | 'retirement_pre'
  | 'retirement_post'
  | 'invest_voluntary'
  | 'invest_guaranteed'
  | 'employee_benefits'
  | 'employee_benefits_risk'
  | 'employee_benefits_retirement'
  | 'estate_planning'
  | 'tax'
  | 'profile_personal'
  | 'profile_contact'
  | 'profile_identity'
  | 'profile_address'
  | 'profile_employment'
  | 'profile_health'
  | 'profile_family'
  | 'profile_banking'
  | 'profile_risk'
  | 'profile_financial';

export interface ProductKey {
  id: string;
  category: ProductKeyCategory;
  name: string;
  description: string;
  dataType: 'number' | 'currency' | 'percentage' | 'date' | 'text' | 'boolean';
  isCalculated?: boolean; // True for totals/calculated fields, false/undefined for assignable fields
  calculatedFrom?: string[]; // Array of key IDs that this total is calculated from
  isRecommendation?: boolean; // True for keys that store FNA recommended values
}

export interface FieldKeyMapping {
  fieldId: string;
  keyId: string;
  categoryId: string; // The product category (risk_planning, etc.)
}
