/**
 * communication-business-logic.resolveRecipients — scheduler recipient resolution
 * ================================================================================
 *
 * Regression guard for the scheduled-campaign path: a campaign targeting an
 * auto provider group (persisted as type: 'system') must resolve to that
 * group's MEMBERSHIP, not to every client. Previously all non-sys_all system
 * groups fell through to "return allClients".
 *
 * Run: npx vitest run src/supabase/functions/server/__tests__/communication-resolve-recipients.test.ts
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.stubGlobal('Deno', { env: { get: () => 'test' } });

// ── Keyed in-memory KV: profiles, policies, security ────────────────────────
const clone = <T>(v: T): T => (v == null ? v : JSON.parse(JSON.stringify(v)));

const PROFILES: Record<string, unknown> = {
  'user_profile:c1:personal_info': { userId: 'c1', personalInformation: { firstName: 'Ann' } },
  'user_profile:c2:personal_info': { userId: 'c2', personalInformation: { firstName: 'Ben' } },
  'user_profile:c3:personal_info': { userId: 'c3', personalInformation: { firstName: 'Cara' } },
};
const POLICIES: Record<string, unknown> = {
  'policies:client:c1': [{ clientId: 'c1', providerName: 'Hollard', categoryId: 'risk_planning' }],
  'policies:client:c2': [{ clientId: 'c2', providerName: 'Discovery', categoryId: 'medical_aid' }],
  'policies:client:c3': [{ clientId: 'c3', providerName: 'Hollard', categoryId: 'medical_aid' }],
};

vi.mock('../kv_store.tsx', () => ({
  mget: vi.fn(async (keys: string[]) =>
    keys.map((k) => {
      if (k.startsWith('user_profile:')) return clone(PROFILES[k] ?? null);
      if (k.startsWith('policies:client:')) return clone(POLICIES[k] ?? null);
      return null; // security:* etc.
    }),
  ),
  get: vi.fn(async () => null),
  set: vi.fn(async () => {}),
}));

vi.mock('../stderr-logger.ts', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), success: vi.fn(), debug: vi.fn() },
  createModuleLogger: () => ({
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    success: vi.fn(),
    debug: vi.fn(),
  }),
}));

vi.mock('../email-service.ts', () => ({
  sendEmail: vi.fn(),
  createEmailTemplate: vi.fn((html: string) => html),
}));

vi.mock('jsr:@supabase/supabase-js@2.49.8', () => ({ createClient: vi.fn() }));

// repo: cache miss, then return the stored group on demand
const { getGroup, getGroupMembersCache, setGroupMembersCache } = vi.hoisted(() => ({
  getGroup: vi.fn(),
  getGroupMembersCache: vi.fn(),
  setGroupMembersCache: vi.fn(),
}));
vi.mock('../communication-repo.ts', () => ({
  getGroup,
  getGroupMembersCache,
  setGroupMembersCache,
}));

import { resolveRecipients } from '../communication-business-logic.ts';
import type { SupabaseAdminClient } from '../communication-types.ts';

const supabase = {
  auth: {
    admin: {
      listUsers: async () => ({
        data: {
          users: [
            { id: 'c1', email: 'c1@x.com' },
            { id: 'c2', email: 'c2@x.com' },
            { id: 'c3', email: 'c3@x.com' },
          ],
        },
        error: null,
      }),
    },
  },
} as unknown as SupabaseAdminClient;

beforeEach(() => {
  vi.clearAllMocks();
  getGroupMembersCache.mockResolvedValue(null); // force fresh calculation
});

describe('resolveRecipients — provider (system) group', () => {
  it('resolves a sys_provider_* group to its membership, NOT all clients', async () => {
    getGroup.mockResolvedValue({
      id: 'sys_provider_hollard',
      name: 'All Hollard Clients',
      type: 'system',
      autoGenerated: true,
      clientIds: [],
      filterConfig: { productFilters: [{ provider: 'Hollard' }] },
    });

    const recipients = await resolveRecipients(
      {
        recipientType: 'group',
        selectedRecipients: [],
        selectedGroup: { id: 'sys_provider_hollard', type: 'system' },
      },
      supabase,
    );

    // c1 (Hollard) and c3 (Hollard) match; c2 (Discovery) does not.
    expect(recipients.map((r) => r.id).sort()).toEqual(['c1', 'c3']);
    expect(recipients).toHaveLength(2);
  });

  it('still returns every client for the sys_all system group', async () => {
    const recipients = await resolveRecipients(
      {
        recipientType: 'group',
        selectedRecipients: [],
        selectedGroup: { id: 'sys_all', type: 'system' },
      },
      supabase,
    );

    expect(recipients.map((r) => r.id).sort()).toEqual(['c1', 'c2', 'c3']);
  });
});
